### ISSUE TITLE
Cant use commands "accelerate launch --num_cpu_threads_per_process 12 lora_train_popup.py"

### ISSUE THREAD

**Issue by UBBK** [derrian-distro/LoRA_Easy_Training_Scripts#1]
This error happens when i use "accelerate launch --num_cpu_threads_per_process 12 lora_train_popup.py"

Traceback (most recent call last):
  File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\...\stable-diffusion-webui\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "E:\...\stable-diffusion-webui\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 43, in main
    args.func(args)
  File "E:\...\stable-diffusion-webui\venv\lib\site-packages\accelerate\commands\launch.py", line 747, in launch_command
    defaults = load_config_from_file(args.config_file)
  File "E:\...\stable-diffusion-webui\venv\lib\site-packages\accelerate\commands\config\config_args.py", line 64, in load_config_from_file
    return config_class.from_yaml_file(yaml_file=config_file)
  File "E:\...\stable-diffusion-webui\venv\lib\site-packages\accelerate\commands\config\config_args.py", line 117, in from_yaml_file
    return cls(**config_dict)
TypeError: ClusterConfig.__init__() got an unexpected keyword argument 'command_file'

**Comment by UBBK** [comment]
tried a fresh install of SD script. Gives ERROR: "Invalid requirement: 'torch1.12.1+cu116'" at the very beginning

**Comment by derrian-distro** [comment]
Hi, 
It looks like you are trying to run this from your *webUI* folder. The webui folder won't work for this as the script is for Kohya's **SD-Scripts**. please make sure you put this into the root folder of your install of Kohya's **SD-Scripts** repo [Github](https://github.com/kohya-ss/sd-scripts). 

This script is not intended to be a complete installer but rather to help you use your already installed setup. I might make an installer, but it probably won't be for a few days at least.

That being said, if you have any issues with installing **SD-Scripts** please refer [here](https://rentry.org/HDGLoRaIssues) to help you solve them, if that doesn't work then come back here, I'll try to help you.

**Comment by UBBK** [comment]
(venv) PS C:\...\sd-scripts> accelerate launch --num_cpu_threads_per_process 12 lora_train_popup.py
>>
accelerate : The term 'accelerate' is not recognized as the name of a cmdlet, function, script file, or operable progra
m. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ accelerate launch --num_cpu_threads_per_process 12 lora_train_popup.p ...
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (accelerate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

This is what the new script gives as an error now

**Comment by derrian-distro** [comment]
do you have sd-scripts properly installed? you must install sd-scripts first before using this, this only makes using sd-scripts easier, it does not install sd-scripts for you.

link to where you can download and install sd-scripts https://github.com/kohya-ss/sd-scripts
this is a standalone thing, it *does not* go into the webui folder

**Comment by UBBK** [comment]
Yes i do have it installed.

**Comment by derrian-distro** [comment]
then you didn't set up accelerate correctly, did you move all of the files within the bitsandbytes folder into your venv?

**Comment by UBBK** [comment]
No i followed rentry guide which didnt tell anything about moving bitsandbytes into venv. Only put them into appdata

**Comment by derrian-distro** [comment]
from the rentry guide
```cp .\bitsandbytes_windows\*.dll .\venv\Lib\site-packages\bitsandbytes\
cp .\bitsandbytes_windows\cextension.py .\venv\Lib\site-packages\bitsandbytes\cextension.py
cp .\bitsandbytes_windows\main.py .\venv\Lib\site-packages\bitsandbytes\cuda_setup\main.py```

**Comment by UBBK** [comment]
oh if it is automatic i did it yes. Copy pasted the command.

**Comment by derrian-distro** [comment]
which venv do you have active? is it the one for webui or sd-scripts?

**Comment by UBBK** [comment]
Ah, thanks i think this was the problem. Still stuck with an endless paging file too small error but thats a whole different story o7

**Comment by derrian-distro** [comment]
ah I know how to fix that one as well, give me a moment to find the exact instructions

but the long story short is that windows sucks at managing page files

**Comment by derrian-distro** [comment]
actually this guide does a good job of explaining how to do it, I suggest you change it to the `16384` that's in the guide as well, I set mine to that and it worked for me.

https://mcci.com/support/guides/how-to-change-the-windows-pagefile-size/

**Comment by UBBK** [comment]
my GPU VRAM is 8GM RAM is 16 GB. Before change pagefile size was 16GB. increased it to 25GB still getting same error.

```
 CUDA SETUP: Loading binary C:\Users\...\sd-scripts\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
use 8-bit Adam optimizer
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 5
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 5
  num epochs / epoch数: 1
  batch size per device / バッチサイズ: 1
  total train batch size (with parallel & distributed & accumulation) / 総バッチサイズ（並列学習、勾配合計含む）: 1
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 5
steps:   0%|                                                                                     | 0/5 [00:00<?, ?it/s]epoch 1/1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\...\sd-scripts\lora_train_popup.py", line 8, in <module>
    import train_network
  File "C:\Users\...\sd-scripts\train_network.py", line 8, in <module>
    import torch
  File "C:\Users\...\sd-scripts\venv\lib\site-packages\torch\__init__.py", line 129, in <module>
    raise err
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Users\...\sd-scripts\venv\lib\site-packages\torch\lib\cusolver64_11.dll" or one of its dependencies.
```

**Comment by derrian-distro** [comment]
alright then, you actually will probably want to set it smaller then, likely 8192 or so.
I think it's dependent on how much system ram you have, I have 32gb so half, 16384 worked for me

**Comment by UBBK** [comment]
Haha even more errors now o_O
```
CUDA SETUP: Loading binary C:\Users\...\sd-scripts\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
use 8-bit Adam optimizer
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 5
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 5
  num epochs / epoch数: 1
  batch size per device / バッチサイズ: 1
  total train batch size (with parallel & distributed & accumulation) / 総バッチサイズ（並列学習、勾配合計含む）: 1
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 5
steps:   0%|                                                                                     | 0/5 [00:00<?, ?it/s]epoch 1/1
Traceback (most recent call last):
  File "C:\Users\...\sd-scripts\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The paging file is too small for this operation to complete.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\...\sd-scripts\lora_train_popup.py", line 8, in <module>
    import train_network
  File "C:\Users\...\sd-scripts\train_network.py", line 9, in <module>
    from accelerate.utils import set_seed
  File "C:\Users\...\sd-scripts\venv\lib\site-packages\accelerate\__init__.py", line 7, in <module>
    from .accelerator import Accelerator
  File "C:\Users\...\sd-scripts\venv\lib\site-packages\accelerate\accelerator.py", line 27, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "C:\Users\...\sd-scripts\venv\lib\site-packages\accelerate\checkpointing.py", line 24, in <module>
    from .utils import (
  File "C:\Users\...\sd-scripts\venv\lib\site-packages\accelerate\utils\__init__.py", line 103, in <module>
    from .megatron_lm import (
  File "C:\Users\...\sd-scripts\venv\lib\site-packages\accelerate\utils\megatron_lm.py", line 32, in <module>
    from transformers.modeling_outputs import (
  File "C:\Users\...\sd-scripts\venv\lib\site-packages\transformers\__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "C:\Users\...\sd-scripts\venv\lib\site-packages\transformers\dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version, require_version_core
  File "C:\Users\...\sd-scripts\venv\lib\site-packages\transformers\utils\__init__.py", line 34, in <module>
    from .generic import (
  File "C:\Users\...\sd-scripts\venv\lib\site-packages\transformers\utils\generic.py", line 33, in <module>
    import tensorflow as tf
  File "C:\Users\...\sd-scripts\venv\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\...\sd-scripts\venv\lib\site-packages\tensorflow\python\__init__.py", line 36, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "C:\Users\...\sd-scripts\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 77, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "C:\Users\...\sd-scripts\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The paging file is too small for this operation to complete.


Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.
```

**Comment by derrian-distro** [comment]
sheesh, it's still basically giving you a paging file too small error, I don't know man, guess you should increase the page file little by little until it works or your computer crashes. start at 16384 i guess.

**Comment by UBBK** [comment]
just tried up to 30000 still same error.

**Comment by derrian-distro** [comment]
I don't know then, that is the extent of my knowledge

**Comment by UBBK** [comment]
increased it to 48GB and now im getting a different error nice. And yeah thanks for trying o7

```
================================================================================
CUDA SETUP: Loading binary C:\Users\...\sd-scripts\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
use 8-bit Adam optimizer
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 5
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 5
  num epochs / epoch数: 1
  batch size per device / バッチサイズ: 1
  total train batch size (with parallel & distributed & accumulation) / 総バッチサイズ（並列学習、勾配合計含む）: 1
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 5
steps:   0%|                                                                                     | 0/5 [00:00<?, ?it/s]epoch 1/1
Error no kernel image is available for execution on the device at line 89 in file D:\ai\tool\bitsandbytes\csrc\ops.cu
Traceback (most recent call last):
  File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\...\sd-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\...\sd-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\...\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Users\...\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\...\\sd-scripts\\venv\\Scripts\\python.exe', 'lora_train_popup.py']' returned non-zero exit status 1.
```

**Comment by derrian-distro** [comment]
this error is related to the bitsandbytes folder I was talking about before,
so I guess I'll go back to the drawing board. I suggest you delete your sd-scripts folder then reinstall from scratch.

use this guide to set up the environemt
https://rentry.org/lora_train#instructions-for-running-the-training-script

**Comment by derrian-distro** [comment]
there is a new guide, but it has you do the same thing, there's no way around it as that's how you install sd-scripts, that will remain constant until kohya themselves change it.

**Comment by derrian-distro** [comment]
that guide is a bit better at showing how to setup the dataset, but I personally believe that my python script is better for people who are new to lora trainig.

**Comment by UBBK** [comment]
1-Set-ExecutionPolicy Unrestricted and answer A as admin
2-Copy paste into non admin powershell:
```
git clone https://github.com/kohya-ss/sd-scripts.git
cd sd-scripts

python -m venv --system-site-packages venv
.\venv\Scripts\activate

pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116
pip install --upgrade -r requirements.txt
pip install -U -I --no-deps https://github.com/C43H66N12O12S2/stable-diffusion-webui/releases/download/f/xformers-0.0.14.dev0-cp310-cp310-win_amd64.whl

cp .\bitsandbytes_windows\*.dll .\venv\Lib\site-packages\bitsandbytes\
cp .\bitsandbytes_windows\cextension.py .\venv\Lib\site-packages\bitsandbytes\cextension.py
cp .\bitsandbytes_windows\main.py .\venv\Lib\site-packages\bitsandbytes\cuda_setup\main.py

accelerate config
```
3-```
This machine
No distributed training
NO
NO
NO
0
FP16
```
4-https://github.com/derrian-distro/LoRA_Easy_Training_Scripts download scripts and put into sd-scripts folder.
5-```
cd sd-scripts
venv\Scripts\activate
accelerate launch --num_cpu_threads_per_process 12 lora_train_popup.py
```
6-pick nai.ckpt, pick image_dir, change nothing else
7- error

**Comment by derrian-distro** [comment]
hmm, I'm not entirely sure what's going on then. is it still the same error as before?

**Comment by UBBK** [comment]
yeah... This is what pip freeze gives btw.
![sil](https://user-images.githubusercontent.com/116608006/212409614-70b52b73-587d-4fb7-bdae-91d95eed763c.png)

**Comment by derrian-distro** [comment]
So, what gpu do you have exactly? it might be related to that.

**Comment by UBBK** [comment]
1070ti

**Comment by derrian-distro** [comment]
guess you can try installing the cuda toolkit, might help might not, just throwing things out there at this point.
https://developer.nvidia.com/cuda-11-6-0-download-archive?target_os=Windows&target_arch=x86_64&target_version=10

**Comment by UBBK** [comment]
Yeah already tried that too... Weird stuff...

**Comment by derrian-distro** [comment]
guess the only other thing I can say is, move the files in your bitsandbytes folder to your main python folder. its usually in your appdata\local folder somewhere

**Comment by derrian-distro** [comment]
it'll be close to something like this `C:\Users\username\AppData\Local\Programs\Python\Python310\Lib\site-packages\`
make a bitsandbytes folder there and copy over the files to it

**Comment by UBBK** [comment]
Ok found the solution here. 

https://github.com/kohya-ss/sd-scripts/issues/44

**Comment by derrian-distro** [comment]
oh wonderful, sorry I couldn't help you as much as I would have liked, I'll go ahead and close this issue now. have fun training LoRAs.
