### ISSUE TITLE
Error no kernel image is available for execution on the device at line 167

### ISSUE THREAD

**Issue by Apricosma** [derrian-distro/LoRA_Easy_Training_Scripts#10]
Trying to train a LoRA and keep running into this error when using the popup script. Quick googling said that reinstalling PyTorch would help, but it hasn't seemed to helped. I have a GTX 1070ti and i7-7700k if it's any help

Here's the full error:

Error no kernel image is available for execution on the device at line 167 in file D:\ai\tool\bitsandbytes\csrc\ops.cu
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\Documents\sd-scripts\sd-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\USER\Documents\sd-scripts\sd-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\USER\Documents\sd-scripts\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Users\USER\Documents\sd-scripts\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\USER\\Documents\\sd-scripts\\sd-scripts\\venv\\Scripts\\python.exe', 'lora_train_popup.py']' returned non-zero exit status 1.

**Comment by Apricosma** [comment]
**RESOLVED**
Took me hours but the issue is I have a 1070 and the issue was bitsandbytes. Their default .dll's don't seem to support the 1000 series GPU's. 
Using this dll and following the instructions to change the line 118 in cuda_setup/main.py to `return "libbitsandbytes_cudaall.dll` instead of cuda116

The fix
https://github.com/james-things/bitsandbytes-prebuilt-all_arch

**Comment by derrian-distro** [comment]
I actually built that fix into my install scripts, if you skip the cudnn patch, which you should with a 10 series card, it will ask you if you have a 10 series card and automatically apply the fix for you. installers v2, 3, and 4 all have this option in them I believe.

**Comment by derrian-distro** [comment]
also, apologies for not getting to this sooner, I was very busy yesterday.

**Comment by Apricosma** [comment]
I must have missed that option or thought it was for something else, apologies. Hopefully this will be helpful for anyone else that runs into the error.

**Comment by derrian-distro** [comment]
it's no issue, I actually had the idea to add it in because I had helped somebody who had that same issue with a 10X0 card before I created the v2 install scripts!
