### ISSUE TITLE
Problem running install.bat

### ISSUE THREAD

**Issue by JSarvise** [derrian-distro/LoRA_Easy_Training_Scripts#107]
Setting up default config of accelerate
Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 815, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] El sistema no puede encontrar la ruta especificada: 'default_config.yaml' -> 'C:\\Users\\Usuario\\.cache\\huggingface\\accelerate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Usuario\LoRA_Easy_Training_Scripts\installer\installer.py", line 169, in <module>
    main()
  File "C:\Users\Usuario\LoRA_Easy_Training_Scripts\installer\installer.py", line 126, in main
    shutil.move("default_config.yaml", os.path.join(os.environ['USERPROFILE'], ".cache", "huggingface", "accelerate"))
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 835, in move
    copy_function(src, real_dst)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Usuario\\.cache\\huggingface\\accelerate'
Presione una tecla para continuar . . .

**Comment by derrian-distro** [comment]
it wasn't able to create the default config yaml for accelerate, I'm not sure why it isn't working for you, but you can just create the accelerate config by opening up a terminal in the sd_scripts folder, then typing `venv/Scripts/activate` then `accelerate config`

after that respond to the following questions in this order:
```
- This machine
- No distributed training
- NO
- NO
- NO
- all
- fp16
```

**Comment by JSarvise** [comment]
That made the trick now im getting an error when trying to train 

Traceback (most recent call last):
  File "D:\LoRA_Easy_Training_Scripts\sd_scripts\train_network.py", line 873, in <module>
    train(args)
  File "D:\LoRA_Easy_Training_Scripts\sd_scripts\train_network.py", line 262, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "D:\LoRA_Easy_Training_Scripts\sd_scripts\library\train_util.py", line 2810, in get_optimizer
    optimizer = optimizer_class(trainable_params, lr=lr, **optimizer_kwargs)
  File "D:\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\dadaptation\dadapt_adan.py", line 73, in __init__
    if not 0.0 <= betas[2] < 1.0:
IndexError: tuple index out of range
Failed to train because of error:
Command '['D:\\LoRA_Easy_Training_Scripts\\sd_scripts\\venv\\Scripts\\python.exe', 'sd_scripts\\train_network.py', '--config_file=runtime_store\\config.toml', '--dataset_config=runtime_store\\dataset.toml']' returned non-zero exit status 1.

**Comment by derrian-distro** [comment]
D-adapt adan doesn't use betas, go into the second tab of optimizer args and remove it
