### ISSUE TITLE
'requests' is not defined

### ISSUE THREAD

**Issue by misterandy33** [derrian-distro/LoRA_Easy_Training_Scripts#112]
Hi there, I ran into this issue while installing. Please advise.

```
  Running setup.py install for library ... done
  Attempting uninstall: requests
    Found existing installation: requests 2.28.1
    Uninstalling requests-2.28.1:
      Successfully uninstalled requests-2.28.1
```

A little while later...
```
Setting up default config of accelerate
Do you want to install the optional cudnn patch for faster training on high end 30X0 and 40X0 cards? (y/n): y
Traceback (most recent call last):
  File "N:\training\LoRA_Easy_Training_Scripts\installer\installer.py", line 169, in <module>
    main()
  File "N:\training\LoRA_Easy_Training_Scripts\installer\installer.py", line 140, in main
    r = requests.get("https://developer.download.nvidia.com/compute/redist/cudnn/v8.6.0/local_installers/11.8/cudnn-windows-x86_64-8.6.0.163_cuda11-archive.zip")
NameError: name 'requests' is not defined
Press any key to continue . . .
```

**Comment by misterandy33** [comment]
Did not fix using `N:\training\LoRA_Easy_Training_Scripts\sd_scripts\venv\Scripts\python.exe -m pip install requests`:
```
Requirement already satisfied: requests in n:\training\lora_easy_training_scripts\sd_scripts\venv\lib\site-packages (2.28.2)
Requirement already satisfied: charset-normalizer<4,>=2 in n:\training\lora_easy_training_scripts\sd_scripts\venv\lib\site-packages (from requests) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in n:\training\lora_easy_training_scripts\sd_scripts\venv\lib\site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in n:\training\lora_easy_training_scripts\sd_scripts\venv\lib\site-packages (from requests) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in n:\training\lora_easy_training_scripts\sd_scripts\venv\lib\site-packages (from requests) (2022.12.7)
```

Fixed by removing the grey highlighted, and changing the yellow highlighted to `"requests"`.
![image](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/assets/140364676/99cef984-f1f2-40b4-b57e-c56fca870782)

**Comment by maepopi** [comment]
Hey, it was not enough for me, so I added "import requests" at the beginning of the installer.py.

Currently looks like this : 

`import shutil
import sys
import subprocess
import os
from pathlib import Path
from zipfile import ZipFile
import requests



print("installing requests...")
python = sys.executable
subprocess.check_call(
    [python, "-m", "pip", "install", "requests"], stdout=subprocess.DEVNULL
)
`
