### ISSUE TITLE
Missing 'support_caption_dropout' arg after git pull.

### ISSUE THREAD

**Issue by LeMemeDream** [derrian-distro/LoRA_Easy_Training_Scripts#12]
As stated in the title, after git pulling today, lora_train_popup fails due to the following error:

`TypeError: add_dataset_arguments() missing 1 required positional argument: 'support_caption_dropout'`

I haven't changed anything of the sort, and the only thing I've done was git pull, so I'm assuming that must be it. I dug through and added "support_caption_dropout" to the add_dataset_argument args, at which point it gave me a new, different error:

`File "D:\sd-scripts\lora_train_popup.py", line 281, in setup_args
    util.add_dataset_arguments(parser, True, True, support_caption_dropout)
NameError: name 'support_caption_dropout' is not defined`

I'm no expert, so I don't know how 'support_caption_dropout' is supposed to be defined. Is this a new feature, or is it something that broke with the update? 

`Starting popup training...
Traceback (most recent call last):
  File "D:\sd-scripts\lora_train_popup.py", line 660, in <module>
    main()
  File "D:\sd-scripts\lora_train_popup.py", line 228, in main
    setup_args(parser)
  File "D:\sd-scripts\lora_train_popup.py", line 281, in setup_args
    util.add_dataset_arguments(parser, True, True)
TypeError: add_dataset_arguments() missing 1 required positional argument: 'support_caption_dropout'
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\sd-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\sd-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "D:\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\sd-scripts\\venv\\Scripts\\python.exe', 'lora_train_popup.py']' returned non-zero exit status 1.`

**Comment by LeMemeDream** [comment]
Alright, not sure why, but it seems to be pulling with a missing "True" in that space. Anyone having the issue, just tack on another "true" there and it'll fix it.

**Comment by derrian-distro** [comment]
I had updated my scripts a while ago to fix this issue, when git pulling sd-scripts you must also git pull my scripts separately, they will not both update off of one git pull!
