### ISSUE TITLE
When training, can't process Russian language in subset path

### ISSUE THREAD

**Issue by Darkenlord1** [derrian-distro/LoRA_Easy_Training_Scripts#122]
When training, can't process Russian language in subset path.
Errors:
`Traceback (most recent call last):
  File "C:\Users\darkenlord1\Desktop\LoRA_Easy_Training_Scripts\sd_scripts\train_network.py", line 873, in <module>
    train(args)
  File "C:\Users\darkenlord1\Desktop\LoRA_Easy_Training_Scripts\sd_scripts\train_network.py", line 99, in train
    user_config = config_util.load_user_config(args.dataset_config)
  File "C:\Users\darkenlord1\Desktop\LoRA_Easy_Training_Scripts\sd_scripts\library\config_util.py", line 496, in load_user_config
    config = toml.load(file)
  File "C:\Users\darkenlord1\Desktop\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\toml\decoder.py", line 134, in load
    return loads(ffile.read(), _dict, decoder)
  File "C:\Users\darkenlord1\AppData\Local\Programs\Python\Python310\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x97 in position 366: invalid start byte
Failed to train because of error:
Command '['C:\\Users\\darkenlord1\\Desktop\\LoRA_Easy_Training_Scripts\\sd_scripts\\venv\\Scripts\\python.exe', 'sd_scripts\\train_network.py', '--config_file=runtime_store\\config.toml', '--dataset_config=runtime_store\\dataset.toml']' returned non-zero exit status 1.`

**Comment by derrian-distro** [comment]
unfortunately, this is a problem with sd-scripts, I cannot solve this issue, I suggest opening up an issue with sd-scripts
