### ISSUE TITLE
Can't load .TOML file

### ISSUE THREAD

**Issue by Signorlimone** [derrian-distro/LoRA_Easy_Training_Scripts#131]
As per title, everytime I try to load a .TOML it gives me this error:

Traceback (most recent call last):
  File "C:\AI\LoRA_Easy_Training_Scripts\main_ui_files\MainWidget.py", line 199, in load_toml
    self.load_args(args)
  File "C:\AI\LoRA_Easy_Training_Scripts\main_ui_files\MainWidget.py", line 162, in load_args
    self.args_widget.load_args(args)
  File "C:\AI\LoRA_Easy_Training_Scripts\main_ui_files\MainWidget.py", line 307, in load_args
    widget.load_args(args)
  File "C:\AI\LoRA_Easy_Training_Scripts\main_ui_files\NetworkUI.py", line 368, in load_args
    self.load_block_args(args)
  File "C:\AI\LoRA_Easy_Training_Scripts\main_ui_files\NetworkUI.py", line 279, in load_block_args
    self.block_widgets[0].down_widgets[i][1].setValue(val)
TypeError: 'PySide6.QtWidgets.QDoubleSpinBox.setValue' called with wrong argument types:
  PySide6.QtWidgets.QDoubleSpinBox.setValue(str)
Supported signatures:
  PySide6.QtWidgets.QDoubleSpinBox.setValue(float)

Someone had the same problem?

**Comment by derrian-distro** [comment]
hmm, this is an issue I haven't run into. not sure how I'd fix this

**Comment by Signorlimone** [comment]
@derrian-distro no problem, it's a small issue, also it does not happen with all the .TOML

**Comment by vin901** [comment]
@Signorlimone @derrian-distro I don't remember if it was the exact same error message, but similar thing happened to me and it was because when you start it up, it tries to load your last .TOML file, but if you deleted or moved that .TOML file then you get an error and the GUI never loads.
