### ISSUE TITLE
AttributeError: partially initialized module 'triton' has no attribute '_C'

### ISSUE THREAD

**Issue by HolyCheems** [derrian-distro/LoRA_Easy_Training_Scripts#136]
On the `SDXL` Branch, running into this error while attempting to train - heres my entire console output from start to finish:
```
starting validation of args...
starting validation of dataset_args...
validated, starting training...
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: DLL load failed while importing libtriton: The specified module could not be found.
Loading settings from runtime_store\config.toml...
runtime_store\config
prepare tokenizers
update token length: 225
Loading dataset config from runtime_store\dataset.toml
prepare images.
found directory C:/Users/cheems/Documents/AI Datasets/Done/cheems_perona_v3/100_cheems_perona_v3 contains 47 image files
found directory C:/Users/cheems/Documents/AI Datasets/Done/cheems_perona_v3/300_cheems_perona_v3 contains 9 image files
74 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 2
  resolution: (896, 896)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 1024
  bucket_reso_steps: 64
  bucket_no_upscale: False

  [Subset 0 of Dataset 0]
    image_dir: "C:/Users/cheems/Documents/AI Datasets/Done/cheems_perona_v3/100_cheems_perona_v3"
    image_count: 47
    num_repeats: 1
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: None
    caption_extension: .txt

  [Subset 1 of Dataset 0]
    image_dir: "C:/Users/cheems/Documents/AI Datasets/Done/cheems_perona_v3/300_cheems_perona_v3"
    image_count: 9
    num_repeats: 3
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: None
    caption_extension: .txt


[Dataset 0]
loading image sizes.
100%|█████████████████████████████████████████████████████████████████████████████████| 56/56 [00:00<00:00, 143.31it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (448, 1024), count: 1
bucket 1: resolution (512, 1024), count: 1
bucket 2: resolution (576, 1024), count: 1
bucket 3: resolution (640, 1024), count: 7
bucket 4: resolution (704, 1024), count: 10
bucket 5: resolution (768, 1024), count: 12
bucket 6: resolution (832, 960), count: 7
bucket 7: resolution (896, 896), count: 14
bucket 8: resolution (960, 832), count: 7
bucket 9: resolution (1024, 704), count: 6
bucket 10: resolution (1024, 768), count: 8
mean ar error (without repeats): 0.02590932768271566
preparing accelerator
loading model for process 0/1
load StableDiffusion checkpoint: C:/Users/cheems/Documents/stable-diffusion-webui2/models/Stable-diffusion/dynavisionXLAllInOneStylized_alpha036FP16Bakedvae.safetensors
building U-Net
loading U-Net from checkpoint
U-Net:  <All keys matched successfully>
building text encoders
loading text encoders from checkpoint
text encoder 1: <All keys matched successfully>
text encoder 2: <All keys matched successfully>
building VAE
loading VAE from checkpoint
VAE: <All keys matched successfully>
Enable xformers for U-Net
import network module: lycoris.kohya
Using rank adaptation algo: locon
Apply different lora dim for conv layer
Conv Dim: 16, Linear Dim: 8
Apply different alpha value for conv layer
Conv alpha: 4.0, Linear alpha: 1.0
Use Dropout value: 0.0
Create LyCORIS Module
Create LyCORIS Module
create LyCORIS for Text Encoder: 264 modules.
Create LyCORIS Module
create LyCORIS for U-Net: 788 modules.
enable LyCORIS for text encoder
enable LyCORIS for U-Net
prepare optimizer, data loader etc.
Deprecated: use prepare_optimizer_params(text_encoder_lr, unet_lr, learning_rate) instead of prepare_optimizer_params(text_encoder_lr, unet_lr)
bin C:\Users\cheems\Documents\SDXLTrainingUI\sd_scripts\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.dll
Traceback (most recent call last):
  File "C:\Users\cheems\Documents\SDXLTrainingUI\sd_scripts\sdxl_train_network.py", line 176, in <module>
    trainer.train(args)
  File "C:\Users\cheems\Documents\SDXLTrainingUI\sd_scripts\train_network.py", line 325, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "C:\Users\cheems\Documents\SDXLTrainingUI\sd_scripts\library\train_util.py", line 3348, in get_optimizer
    import bitsandbytes as bnb
  File "C:\Users\cheems\Documents\SDXLTrainingUI\sd_scripts\venv\lib\site-packages\bitsandbytes\__init__.py", line 16, in <module>
    from .nn import modules
  File "C:\Users\cheems\Documents\SDXLTrainingUI\sd_scripts\venv\lib\site-packages\bitsandbytes\nn\__init__.py", line 6, in <module>
    from .triton_based_modules import SwitchBackLinear, SwitchBackLinearGlobal, SwitchBackLinearVectorwise, StandardLinear
  File "C:\Users\cheems\Documents\SDXLTrainingUI\sd_scripts\venv\lib\site-packages\bitsandbytes\nn\triton_based_modules.py", line 8, in <module>
    from bitsandbytes.triton.dequantize_rowwise import dequantize_rowwise
  File "C:\Users\cheems\Documents\SDXLTrainingUI\sd_scripts\venv\lib\site-packages\bitsandbytes\triton\dequantize_rowwise.py", line 10, in <module>
    import triton
  File "C:\Users\cheems\Documents\SDXLTrainingUI\sd_scripts\venv\lib\site-packages\triton\__init__.py", line 13, in <module>
    from . import language
  File "C:\Users\cheems\Documents\SDXLTrainingUI\sd_scripts\venv\lib\site-packages\triton\language\__init__.py", line 2, in <module>
    from . import core, extern, libdevice, random
  File "C:\Users\cheems\Documents\SDXLTrainingUI\sd_scripts\venv\lib\site-packages\triton\language\core.py", line 1141, in <module>
    def abs(x):
  File "C:\Users\cheems\Documents\SDXLTrainingUI\sd_scripts\venv\lib\site-packages\triton\runtime\jit.py", line 386, in jit
    return JITFunction(args[0], **kwargs)
  File "C:\Users\cheems\Documents\SDXLTrainingUI\sd_scripts\venv\lib\site-packages\triton\runtime\jit.py", line 315, in __init__
    self.run = self._make_launcher()
  File "C:\Users\cheems\Documents\SDXLTrainingUI\sd_scripts\venv\lib\site-packages\triton\runtime\jit.py", line 282, in _make_launcher
    scope = {"version_key": version_key(), "get_cuda_stream": get_cuda_stream,
  File "C:\Users\cheems\Documents\SDXLTrainingUI\sd_scripts\venv\lib\site-packages\triton\runtime\jit.py", line 82, in version_key
    with open(triton._C.libtriton.__file__, "rb") as f:
AttributeError: partially initialized module 'triton' has no attribute '_C' (most likely due to a circular import)
Failed to train because of error:
Command '['C:\\Users\\cheems\\Documents\\SDXLTrainingUI\\sd_scripts\\venv\\Scripts\\python.exe', 'sd_scripts\\sdxl_train_network.py', '--config_file=runtime_store\\config.toml', '--dataset_config=runtime_store\\dataset.toml']' returned non-zero exit status 1.
```
I've also attached my config toml file if its helpful, the model im training with has a baked in VAE.
[peronasdxlconf.zip](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/files/12371371/peronasdxlconf.zip)

**Comment by derrian-distro** [comment]
hah, triton huh? might just be best to reinstall the venv without triton. it seems to be causing a lot of issues, and on windows doesn't help it seems, so I'll be removing it in the next update anyways. tell me if that fixes the issue!

**Comment by enokyou** [comment]
I have also same problem.

AttributeError: partially initialized module 'triton' has no attribute '_C' (most likely due to a circular import)
Failed to train because of error:
Command '['D:\\stable-diffusion-webui\\LoRA_Easy_Training_Scripts\\sd_scripts\\venv\\Scripts\\python.exe', 'sd_scripts\\train_network.py', '--config_file=runtime_store\\config.toml', '--dataset_config=runtime_store\\dataset.toml']' returned non-zero exit status 1.

This problem occurs even changing the 1.5 model.
If you possess the solution, please tell me it.

**Comment by UBBK** [comment]
same issue.no idea what reinstalling venv is

**Comment by derrian-distro** [comment]
In the sd_scripts folder, you will see a folder name "venv" delete that folder then run the most up to date installer, if the installer asks if you want to install triton, then you are on an older version.

Triton broke at some point, and doesn't really help, so I removed it
