### ISSUE TITLE
No module named 'LoraEasyCustomOptimizer'

### ISSUE THREAD

**Issue by N0repi** [derrian-distro/LoRA_Easy_Training_Scripts#142]
Hey, I am receiving the error below when using the LR Scheduler: cosine annealing warmup restarts

Do you know what might be causing the module to not be found?

```
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
preparing optimizer, data loader etc.
use Prodigy optimizer | {'weight_decay': 0.1, 'betas': (0.9, 0.99), 'd_coef': 2, 'safeguard_warmup': True, 'decouple': True, 'use_bias_correction': True}
Using decoupled weight decay
override steps. steps for 25 epochs is / 指定エポックまでのステップ数: 2450
use LoraEasyCustomOptimizer.CustomOptimizers.CosineAnnealingWarmupRestarts | {'gamma': 0.9, 'min_lr': 1e-06, 'first_cycle_steps': 2404, 'warmup_steps': 120} as lr_scheduler
Traceback (most recent call last):
  File "/mnt/NAS/AI-ML/SD/SD_newer/torch1/LoRA_Easy_Training_Scripts/sd_scripts/train_network.py", line 873, in <module>
    train(args)
  File "/mnt/NAS/AI-ML/SD/SD_newer/torch1/LoRA_Easy_Training_Scripts/sd_scripts/train_network.py", line 289, in train
    lr_scheduler = train_util.get_scheduler_fix(args, optimizer, accelerator.num_processes)
  File "/mnt/NAS/AI-ML/SD/SD_newer/torch1/LoRA_Easy_Training_Scripts/sd_scripts/library/train_util.py", line 2942, in get_scheduler_fix
    lr_scheduler_module = importlib.import_module(".".join(values[:-1]))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
**ModuleNotFoundError: No module named 'LoraEasyCustomOptimizer'**
```

toml parameters

```
[optimizer_args.args]
optimizer_type = "Prodigy"
lr_scheduler = "cosine"
learning_rate = 1.0
lr_scheduler_type = "LoraEasyCustomOptimizer.CustomOptimizers.CosineAnnealingWarmupRestarts"
lr_scheduler_num_cycles = 1
warmup_ratio = 0.05
min_snr_gamma = 5

[optimizer_args.args.lr_scheduler_args]
gamma = 0.9
min_lr = 1e-6

[optimizer_args.args.optimizer_args]
weight_decay = "0.1"
betas = "0.9,0.99"
d_coef = "2"
safeguard_warmup = "True"
decouple = "True"
use_bias_correction = "True"
```

**Comment by derrian-distro** [comment]
it means that the custom optimizer hasn't been installed. How did you install the scripts?

**Comment by N0repi** [comment]
> it means that the custom optimizer hasn't been installed. How did you install the scripts?

I followed the commands Linux outline in the README, except I installed a more recent version of xformers.

https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/blob/main/README.md

**Comment by derrian-distro** [comment]
ah I see, I forgot to add the line from the SDXL branch, which is the working branch, and the one you really should be installing, Even if you aren't training SDXL, it's still more up to date than main branch by a lot

you need to `pip install custom_scheduler` into the venv

**Comment by N0repi** [comment]
Thank you very much for your help! I got it working on the SDXL branch.
