### ISSUE TITLE
error conecction?

### ISSUE THREAD

**Issue by Hilurex** [derrian-distro/LoRA_Easy_Training_Scripts#145]
raceback (most recent call last):
  File "D:\train\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\urllib3\response.py", line 444, in _error_catcher
    yield
  File "D:\train\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\urllib3\response.py", line 567, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "D:\train\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\urllib3\response.py", line 533, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "C:\Users\Ricardo\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 465, in read
    s = self.fp.read(amt)
  File "C:\Users\Ricardo\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Ricardo\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Ricardo\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\train\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\requests\models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "D:\train\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\urllib3\response.py", line 628, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "D:\train\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\urllib3\response.py", line 566, in read
    with self._error_catcher():
  File "C:\Users\Ricardo\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\train\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\urllib3\response.py", line 449, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\train\LoRA_Easy_Training_Scripts\sd_scripts\train_network.py", line 873, in <module>
    train(args)
  File "D:\train\LoRA_Easy_Training_Scripts\sd_scripts\train_network.py", line 168, in train
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype, accelerator)
  File "D:\train\LoRA_Easy_Training_Scripts\sd_scripts\library\train_util.py", line 3149, in load_target_model
    text_encoder, vae, unet, load_stable_diffusion_format = _load_target_model(
  File "D:\train\LoRA_Easy_Training_Scripts\sd_scripts\library\train_util.py", line 3115, in _load_target_model
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(args.v2, name_or_path, device)
  File "D:\train\LoRA_Easy_Training_Scripts\sd_scripts\library\model_util.py", line 904, in load_models_from_stable_diffusion_checkpoint
    text_model = CLIPTextModel.from_pretrained("openai/clip-vit-large-patch14").to(device)
  File "D:\train\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\transformers\modeling_utils.py", line 2208, in from_pretrained
    resolved_archive_file = cached_file(pretrained_model_name_or_path, filename, **cached_file_kwargs)
  File "D:\train\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\transformers\utils\hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "D:\train\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\train\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\huggingface_hub\file_download.py", line 1326, in hf_hub_download
    http_get(
  File "D:\train\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\huggingface_hub\file_download.py", line 538, in http_get
    for chunk in r.iter_content(chunk_size=10 * 1024 * 1024):
  File "D:\train\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\requests\models.py", line 822, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out

**Comment by derrian-distro** [comment]
that looks like a connection issue to huggingface, I can't do anything about that unfortunately
