### ISSUE TITLE
i am error   "must be divisible by 4 to view Byte as Float"

### ISSUE THREAD

**Issue by Hilurex** [derrian-distro/LoRA_Easy_Training_Scripts#147]
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
D:\train\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\transformers\modeling_utils.py:402: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(checkpoint_file, framework="pt") as f:
Traceback (most recent call last):
  File "D:\train\LoRA_Easy_Training_Scripts\sd_scripts\train_network.py", line 873, in <module>
    train(args)
  File "D:\train\LoRA_Easy_Training_Scripts\sd_scripts\train_network.py", line 168, in train
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype, accelerator)
  File "D:\train\LoRA_Easy_Training_Scripts\sd_scripts\library\train_util.py", line 3149, in load_target_model
    text_encoder, vae, unet, load_stable_diffusion_format = _load_target_model(
  File "D:\train\LoRA_Easy_Training_Scripts\sd_scripts\library\train_util.py", line 3115, in _load_target_model
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(args.v2, name_or_path, device)
  File "D:\train\LoRA_Easy_Training_Scripts\sd_scripts\library\model_util.py", line 904, in load_models_from_stable_diffusion_checkpoint
    text_model = CLIPTextModel.from_pretrained("openai/clip-vit-large-patch14").to(device)
  File "D:\train\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\transformers\modeling_utils.py", line 2301, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "D:\train\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\transformers\modeling_utils.py", line 413, in load_state_dict
    return safe_load_file(checkpoint_file)
  File "D:\train\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\safetensors\torch.py", line 100, in load_file
    result[k] = f.get_tensor(k)
RuntimeError: self.size(-1) must be divisible by 4 to view Byte as Float (different element sizes), but got 11270793

**Comment by derrian-distro** [comment]
looks like it failed to load the base model, not much more I can do to help as that is more related to sd-scripts, I suggest moving this over there to get a better help.
