### ISSUE TITLE
bitsandbytes error

### ISSUE THREAD

**Issue by CyberLykan** [derrian-distro/LoRA_Easy_Training_Scripts#152]
Not sure what's causing the issue here. I tried to replicate the CivitAI style training settings (anime model) using the application defaults as the base.
Application was installed with torch 2.0.1, no 30x0 and 40x0 patch, yes 10x0 patch.

Log:
```
starting validation of args...
starting validation of dataset_args...
C:\Users\joe\Desktop\test_output\last.safetensors
validated, starting training...
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Loading settings from runtime_store\config.toml...
runtime_store\config
prepare tokenizer
update token length: 225
Loading dataset config from runtime_store\dataset.toml
prepare images.
found directory C:/Users/joe/Desktop/test contains 1 image files
neither caption file nor class tokens are found. use empty caption for C:/Users/joe/Desktop/test\103207318_p0.png / キャプションファイルもclass tokenも見つかりませんでした。空のキャプションを使用します: C:/Users/joe/Desktop/test\103207318_p0.png
No caption file found for 1 images. Training will continue without captions for these images. If class token exists, it will be used. / 1枚の画像にキャプションファイルが見つかりませんでした。これらの画像についてはキャプションなしで学習を続 行します。class tokenが存在する場合はそれを使います。
C:/Users/joe/Desktop/test\103207318_p0.png
200 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 6
  resolution: (512, 512)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 1024
  bucket_reso_steps: 64
  bucket_no_upscale: False

  [Subset 0 of Dataset 0]
    image_dir: "C:/Users/joe/Desktop/test"
    image_count: 1
    num_repeats: 200
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: None
    caption_extension: .txt


[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (512, 512), count: 200
mean ar error (without repeats): 0.0008707009142359112
preparing accelerator
loading model for process 0/1
load StableDiffusion checkpoint: D:/My Stuff/Extra Stuff/stable-diffusion-webui/models/Stable-diffusion/animefull-final-pruned.safetensors
UNet2DConditionModel: 64, 8, 768, False, False
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
import network module: networks.lora
create LoRA network. base dim (rank): 32, alpha: 16.0
neuron dropout: p=None, rank dropout: p=None, module dropout: p=None
create LoRA for Text Encoder:
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
prepare optimizer, data loader etc.
Traceback (most recent call last):
  File "D:\My Stuff\Extra Stuff\LoRA_Easy_Training_Scripts\sd_scripts\library\train_util.py", line 3410, in get_optimizer
    import bitsandbytes as bnb
  File "D:\My Stuff\Extra Stuff\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "D:\My Stuff\Extra Stuff\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "D:\My Stuff\Extra Stuff\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "D:\My Stuff\Extra Stuff\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "D:\My Stuff\Extra Stuff\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "D:\My Stuff\Extra Stuff\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\bitsandbytes\cextension.py", line 8, in <module>
    from bitsandbytes.cuda_setup.main import CUDASetup
  File "D:\My Stuff\Extra Stuff\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 21, in <module>
    from .paths import determine_cuda_runtime_lib_path
ModuleNotFoundError: No module named 'bitsandbytes.cuda_setup.paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\My Stuff\Extra Stuff\LoRA_Easy_Training_Scripts\sd_scripts\train_network.py", line 1006, in <module>
    trainer.train(args)
  File "D:\My Stuff\Extra Stuff\LoRA_Easy_Training_Scripts\sd_scripts\train_network.py", line 335, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "D:\My Stuff\Extra Stuff\LoRA_Easy_Training_Scripts\sd_scripts\library\train_util.py", line 3412, in get_optimizer
    raise ImportError("No bitsandbytes / bitsandbytesがインストールされていないようです")
ImportError: No bitsandbytes / bitsandbytesがインストールされていないようです
Failed to train because of error:
Command '['D:\\My Stuff\\Extra Stuff\\LoRA_Easy_Training_Scripts\\sd_scripts\\venv\\Scripts\\python.exe', 'sd_scripts\\train_network.py', '--config_file=runtime_store\\config.toml', '--dataset_config=runtime_store\\dataset.toml']' returned non-zero exit status 1.
```

Config:
```
[[subsets]]
num_repeats = 200
keep_tokens = 0
caption_extension = ".txt"
shuffle_caption = false
flip_aug = false
color_aug = false
random_crop = false
is_reg = false
image_dir = "C:/Users/joe/Desktop/test"

[noise_args]

[sample_args]

[logging_args]

[general_args.args]
pretrained_model_name_or_path = "D:/My Stuff/Extra Stuff/stable-diffusion-webui/models/Stable-diffusion/animefull-final-pruned.safetensors"
mixed_precision = "fp16"
seed = 23
clip_skip = 2
max_data_loader_n_workers = 1
persistent_data_loader_workers = true
max_token_length = 225
prior_loss_weight = 1.0
max_train_epochs = 10

[general_args.dataset_args]
resolution = 512
batch_size = 6

[network_args.args]
network_dim = 32
network_alpha = 16.0

[optimizer_args.args]
optimizer_type = "AdamW8bit"
lr_scheduler = "cosine_with_restarts"
learning_rate = 0.0001
max_grad_norm = 1.0
unet_lr = 0.0005
text_encoder_lr = 5e-5
lr_scheduler_num_cycles = 3
min_snr_gamma = 5

[saving_args.args]
output_dir = "C:/Users/joe/Desktop/test_output"
save_precision = "fp16"
save_model_as = "safetensors"

[bucket_args.dataset_args]
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 1024
bucket_reso_steps = 64

[optimizer_args.args.optimizer_args]
weight_decay = "0.1"
```

**Comment by CyberLykan** [comment]
> 200 repeats... what are you trying to do?

Don't ask me, ask CivitAI. ¯\\\_(ツ)_/¯

**Comment by Jelosus2** [comment]
> > 200 repeats... what are you trying to do?
> 
> Don't ask me, ask CivitAI. ¯\_(ツ)_/¯

But are you trying to do some character, concept, style... I could help you with tweaking the settings so you can get good results if you want :)

**Comment by CyberLykan** [comment]
Is there any fix or workaround currently?

**Comment by iA-cooder** [comment]
Getting the same error I think. Torch 2.0.1, no 30x0/40x0 patch, no 10x0 patch.
Log:
```
starting validation of args...
starting validation of dataset_args...
C:\Users\Red\Documents\sd\LoRA_Easy_Training_Scripts\outputs\mizuryukei.safetensors
validated, starting training...
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Loading settings from runtime_store\config.toml...
runtime_store\config
prepare tokenizer
update token length: 225
Loading dataset config from runtime_store\dataset.toml
prepare images.
found directory C:/Users/Red/Documents/sd/LoRA_Easy_Training_Scripts/inputs/mizuryu_kei contains 371 image files
1113 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 2
  resolution: (576, 576)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 1024
  bucket_reso_steps: 64
  bucket_no_upscale: False

  [Subset 0 of Dataset 0]
    image_dir: "C:/Users/Red/Documents/sd/LoRA_Easy_Training_Scripts/inputs/mizuryu_kei"
    image_count: 371
    num_repeats: 3
    shuffle_caption: True
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: True
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: None
    caption_extension: .txt


[Dataset 0]
loading image sizes.
100%|███████████████████████████████████████████████████████████████████████████████| 371/371 [00:01<00:00, 238.90it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (256, 1024), count: 36
bucket 1: resolution (320, 896), count: 81
bucket 2: resolution (320, 960), count: 21
bucket 3: resolution (320, 1024), count: 21
bucket 4: resolution (384, 768), count: 39
bucket 5: resolution (384, 832), count: 24
bucket 6: resolution (448, 704), count: 327
bucket 7: resolution (512, 640), count: 129
bucket 8: resolution (576, 576), count: 12
bucket 9: resolution (640, 512), count: 393
bucket 10: resolution (704, 448), count: 27
bucket 11: resolution (768, 384), count: 3
mean ar error (without repeats): 0.06436148373081436
preparing accelerator
loading model for process 0/1
load StableDiffusion checkpoint: C:/Users/Red/Documents/sd/stable-diffusion-webui/models/Stable-diffusion/nai.ckpt
UNet2DConditionModel: 64, 8, 768, False, False
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
load VAE: C:/Users/Red/Documents/sd/stable-diffusion-webui/models/Stable-diffusion/nai.vae.pt
additional VAE loaded
Enable xformers for U-Net
import network module: networks.lora
[Dataset 0]
caching latents.
checking cache validity...
100%|████████████████████████████████████████████████████████████████████████████████████████| 371/371 [00:00<?, ?it/s]
caching latents...
100%|████████████████████████████████████████████████████████████████████████████████| 371/371 [01:12<00:00,  5.10it/s]
create LoRA network. base dim (rank): 96, alpha: 48.0
neuron dropout: p=None, rank dropout: p=None, module dropout: p=None
apply LoRA to Conv2d with kernel size (3,3). dim (rank): 32, alpha: 16.0
create LoRA for Text Encoder:
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 278 modules.
enable LoRA for text encoder
enable LoRA for U-Net
prepare optimizer, data loader etc.
Traceback (most recent call last):
  File "C:\Users\Red\Documents\sd\LoRA_Easy_Training_Scripts\sd_scripts\library\train_util.py", line 3410, in get_optimizer
    import bitsandbytes as bnb
  File "C:\Users\Red\Documents\sd\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Users\Red\Documents\sd\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Users\Red\Documents\sd\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Users\Red\Documents\sd\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Users\Red\Documents\sd\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\Users\Red\Documents\sd\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\bitsandbytes\cextension.py", line 8, in <module>
    from bitsandbytes.cuda_setup.main import CUDASetup
  File "C:\Users\Red\Documents\sd\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 21, in <module>
    from .paths import determine_cuda_runtime_lib_path
ModuleNotFoundError: No module named 'bitsandbytes.cuda_setup.paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Red\Documents\sd\LoRA_Easy_Training_Scripts\sd_scripts\train_network.py", line 1006, in <module>
    trainer.train(args)
  File "C:\Users\Red\Documents\sd\LoRA_Easy_Training_Scripts\sd_scripts\train_network.py", line 335, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "C:\Users\Red\Documents\sd\LoRA_Easy_Training_Scripts\sd_scripts\library\train_util.py", line 3412, in get_optimizer
    raise ImportError("No bitsandbytes / bitsandbytesがインストールされていないようです")
ImportError: No bitsandbytes / bitsandbytesがインストールされていないようです
Failed to train because of error:
Command '['C:\\Users\\Red\\Documents\\sd\\LoRA_Easy_Training_Scripts\\sd_scripts\\venv\\Scripts\\python.exe', 'sd_scripts\\train_network.py', '--config_file=runtime_store\\config.toml', '--dataset_config=runtime_store\\dataset.toml']' returned non-zero exit status 1.
```

Config:
```
[[subsets]]
num_repeats = 3
keep_tokens = 0
caption_extension = ".txt"
shuffle_caption = true
flip_aug = true
is_reg = false
image_dir = "C:/Users/Red/Documents/sd/LoRA_Easy_Training_Scripts/inputs/mizuryu_kei"

[noise_args]

[sample_args]

[logging_args]

[general_args.args]
pretrained_model_name_or_path = "C:/Users/Red/Documents/sd/stable-diffusion-webui/models/Stable-diffusion/nai.ckpt"
mixed_precision = "fp16"
seed = 23
clip_skip = 2
max_data_loader_n_workers = 1
persistent_data_loader_workers = true
max_token_length = 225
prior_loss_weight = 1.0
vae = "C:/Users/Red/Documents/sd/stable-diffusion-webui/models/Stable-diffusion/nai.vae.pt"
max_train_epochs = 16
xformers = true
cache_latents = true

[general_args.dataset_args]
resolution = 576
batch_size = 2

[network_args.args]
network_dim = 96
network_alpha = 48.0
fa = false

[optimizer_args.args]
optimizer_type = "AdamW8bit"
lr_scheduler = "cosine_with_restarts"
learning_rate = 0.0001
max_grad_norm = 1.0
lr_scheduler_num_cycles = 3
text_encoder_lr = 5e-5

[saving_args.args]
output_dir = "C:/Users/Red/Documents/sd/LoRA_Easy_Training_Scripts/outputs"
save_precision = "fp16"
save_model_as = "safetensors"
save_every_n_epochs = 2
tag_occurrence = true
save_toml = true

[bucket_args.dataset_args]
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 1024
bucket_reso_steps = 64

[network_args.args.network_args]
conv_dim = 32
conv_alpha = 16.0

[optimizer_args.args.optimizer_args]
weight_decay = "0.1"
betas = "0.9,0.99"
```

**Comment by CyberLykan** [comment]
Might still be broken on latest dev build.

```
starting validation of args...
starting validation of dataset_args...
C:\Users\joe\Desktop\test_output\last.safetensors
validated, starting training...
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Loading settings from runtime_store\config.toml...
runtime_store\config
prepare tokenizer
update token length: 225
Loading dataset config from runtime_store\dataset.toml
prepare images.
found directory C:/Users/joe/Desktop/test contains 1 image files
neither caption file nor class tokens are found. use empty caption for C:/Users/joe/Desktop/test\103207318_p0.png / キャプションファイルもclass tokenも見つかりませんでした。空のキャプションを使用します: C:/Users/joe/Desktop/test\103207318_p0.png
No caption file found for 1 images. Training will continue without captions for these images. If class token exists, it will be used. / 1枚の画像にキャプションファイルが見つかりませんでした。これらの画像についてはキャプションなしで学習を続 行します。class tokenが存在する場合はそれを使います。
C:/Users/joe/Desktop/test\103207318_p0.png
200 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 6
  resolution: (512, 512)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 1024
  bucket_reso_steps: 64
  bucket_no_upscale: False

  [Subset 0 of Dataset 0]
    image_dir: "C:/Users/joe/Desktop/test"
    image_count: 1
    num_repeats: 200
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: None
    caption_extension: .txt


[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.03it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (512, 512), count: 200
mean ar error (without repeats): 0.0008707009142359112
preparing accelerator
loading model for process 0/1
load StableDiffusion checkpoint: D:/My Stuff/Extra Stuff/stable-diffusion-webui/models/Stable-diffusion/animefull-final-pruned.safetensors
UNet2DConditionModel: 64, 8, 768, False, False
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
Enable xformers for U-Net
import network module: networks.lora
create LoRA network. base dim (rank): 32, alpha: 16.0
neuron dropout: p=None, rank dropout: p=None, module dropout: p=None
create LoRA for Text Encoder:
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
prepare optimizer, data loader etc.
Traceback (most recent call last):
  File "D:\My Stuff\Extra Stuff\LoRA_Easy_Training_Scripts\sd_scripts\library\train_util.py", line 3433, in get_optimizer
    import bitsandbytes as bnb
  File "D:\My Stuff\Extra Stuff\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "D:\My Stuff\Extra Stuff\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "D:\My Stuff\Extra Stuff\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "D:\My Stuff\Extra Stuff\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "D:\My Stuff\Extra Stuff\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "D:\My Stuff\Extra Stuff\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\bitsandbytes\cextension.py", line 8, in <module>
    from bitsandbytes.cuda_setup.main import CUDASetup
  File "D:\My Stuff\Extra Stuff\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 21, in <module>
    from .paths import determine_cuda_runtime_lib_path
ModuleNotFoundError: No module named 'bitsandbytes.cuda_setup.paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\My Stuff\Extra Stuff\LoRA_Easy_Training_Scripts\sd_scripts\train_network.py", line 1012, in <module>
    trainer.train(args)
  File "D:\My Stuff\Extra Stuff\LoRA_Easy_Training_Scripts\sd_scripts\train_network.py", line 342, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "D:\My Stuff\Extra Stuff\LoRA_Easy_Training_Scripts\sd_scripts\library\train_util.py", line 3435, in get_optimizer
    raise ImportError("No bitsandbytes / bitsandbytesがインストールされていないようです")
ImportError: No bitsandbytes / bitsandbytesがインストールされていないようです
Failed to train because of error:
Command '['D:\\My Stuff\\Extra Stuff\\LoRA_Easy_Training_Scripts\\sd_scripts\\venv\\Scripts\\python.exe', 'sd_scripts\\train_network.py', '--config_file=runtime_store\\config.toml', '--dataset_config=runtime_store\\dataset.toml']' returned non-zero exit status 1.
```

**Comment by Jelosus2** [comment]
Try to activate the venv and use this command `pip install bitsandbytes-windows`
