### ISSUE TITLE
__init__() got an unexpected keyword argument 'project_dir'

### ISSUE THREAD

**Issue by lIlIlI11111111** [derrian-distro/LoRA_Easy_Training_Scripts#166]
I've tried updating as well as reinstalling, but this issue keeps persisting. I have tried with the sampling option enabled and disabled and with logging enabled and disabled. This issue seems to also be present in koyha_ss, potentially: https://github.com/bmaltais/kohya_ss/issues/1198#issue-1804645683. I think maybe the way `accelerate` takes in arguments might have changed in its syntax? I am on Linux, which might matter, or maybe not?

[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████████████| 423/423 [00:00<00:00, 11714.23it/s]
Traceback (most recent call last):
prepare dataset
preparing accelerator
  File "/home/username/StableDiffThings/LoRA Training/LoRA_Easy_Training_Scripts/sd_scripts/train_network.py", line 1006, in <module>
    trainer.train(args)
  File "/home/username/StableDiffThings/LoRA Training/LoRA_Easy_Training_Scripts/sd_scripts/train_network.py", line 216, in train
    accelerator = train_util.prepare_accelerator(args)
  File "/home/username/StableDiffThings/LoRA Training/LoRA_Easy_Training_Scripts/sd_scripts/library/train_util.py", line 3775, in prepare_accelerator
    accelerator = Accelerator(
TypeError: __init__() got an unexpected keyword argument 'project_dir'

**Comment by derrian-distro** [comment]
hmm... that might be it, I'm not sure entirely. I'll have to look into it when I have time

**Comment by Jelosus2** [comment]
Seems to be fixed so I'm gonna close the issue
