### ISSUE TITLE
pip subprocess to install build dependencies did not run successfully.

### ISSUE THREAD

**Issue by jdroo** [derrian-distro/LoRA_Easy_Training_Scripts#174]
Got me an error, I did the upgrade to pip like it said, but it seems not to work? help! 

```
C:\StabilityMatrix\LoRA_Easy_Training_Scripts>install.bat
setting execution policy to unrestricted
creating venv and installing requirements
Are you using a 10X0 series card? (y/n): n
Looking in indexes: https://download.pytorch.org/whl/cu118
Collecting torch
  Using cached https://download.pytorch.org/whl/cu118/torch-2.1.2%2Bcu118-cp310-cp310-win_amd64.whl (2722.7 MB)
Collecting torchvision
  Using cached https://download.pytorch.org/whl/cu118/torchvision-0.16.2%2Bcu118-cp310-cp310-win_amd64.whl (4.9 MB)
Collecting networkx
  Using cached https://download.pytorch.org/whl/networkx-3.0-py3-none-any.whl (2.0 MB)
Collecting jinja2
  Using cached https://download.pytorch.org/whl/Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting typing-extensions
  Using cached https://download.pytorch.org/whl/typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Collecting fsspec
  Using cached https://download.pytorch.org/whl/fsspec-2023.4.0-py3-none-any.whl (153 kB)
Collecting sympy
  Using cached https://download.pytorch.org/whl/sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting filelock
  Using cached https://download.pytorch.org/whl/filelock-3.9.0-py3-none-any.whl (9.7 kB)
Collecting numpy
  Using cached https://download.pytorch.org/whl/numpy-1.24.1-cp310-cp310-win_amd64.whl (14.8 MB)
Collecting requests
  Using cached https://download.pytorch.org/whl/requests-2.28.1-py3-none-any.whl (62 kB)
Collecting pillow!=8.3.*,>=5.3.0
  Using cached https://download.pytorch.org/whl/Pillow-9.3.0-cp310-cp310-win_amd64.whl (2.5 MB)
Collecting MarkupSafe>=2.0
  Using cached https://download.pytorch.org/whl/MarkupSafe-2.1.3-cp310-cp310-win_amd64.whl (17 kB)
Collecting charset-normalizer<3,>=2
  Using cached https://download.pytorch.org/whl/charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting certifi>=2017.4.17
  Using cached https://download.pytorch.org/whl/certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached https://download.pytorch.org/whl/urllib3-1.26.13-py2.py3-none-any.whl (140 kB)
Collecting idna<4,>=2.5
  Using cached https://download.pytorch.org/whl/idna-3.4-py3-none-any.whl (61 kB)
Collecting mpmath>=0.19
  Using cached https://download.pytorch.org/whl/mpmath-1.3.0-py3-none-any.whl (536 kB)
Installing collected packages: mpmath, urllib3, typing-extensions, sympy, pillow, numpy, networkx, MarkupSafe, idna, fsspec, filelock, charset-normalizer, certifi, requests, jinja2, torch, torchvision
Successfully installed MarkupSafe-2.1.3 certifi-2022.12.7 charset-normalizer-2.1.1 filelock-3.9.0 fsspec-2023.4.0 idna-3.4 jinja2-3.1.2 mpmath-1.3.0 networkx-3.0 numpy-1.24.1 pillow-9.3.0 requests-2.28.1 sympy-1.12 torch-2.1.2+cu118 torchvision-0.16.2+cu118 typing-extensions-4.4.0 urllib3-1.26.13
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\certifi already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\certifi-2022.12.7.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\charset_normalizer already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\charset_normalizer-2.1.1.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\filelock already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\filelock-3.9.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\fsspec already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\fsspec-2023.4.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\functorch already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\idna already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\idna-3.4.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\isympy.py already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\jinja2 already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\Jinja2-3.1.2.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\markupsafe already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\MarkupSafe-2.1.3.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\mpmath already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\mpmath-1.3.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\networkx already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\networkx-3.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\numpy already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\numpy-1.24.1.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\nvfuser already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\PIL already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\Pillow-9.3.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\requests already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\requests-2.28.1.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\sympy already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\sympy-1.12.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\torch already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\torch-2.1.2+cu118.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\torchgen already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\torchvision already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\torchvision-0.16.2+cu118.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\typing_extensions-4.4.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\typing_extensions.py already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\urllib3 already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\urllib3-1.26.13.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\__pycache__ already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\bin already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\jdroo\appdata\local\programs\python\python310\lib\site-packages\share already exists. Specify --upgrade to force replacement.

[notice] A new release of pip available: 22.2.1 -> 23.3.2
[notice] To update, run: C:\StabilityMatrix\LoRA_Easy_Training_Scripts\sd_scripts\venv\Scripts\python.exe -m pip install --upgrade pip
Obtaining file:///C:/StabilityMatrix/LoRA_Easy_Training_Scripts/sd_scripts (from -r requirements.txt (line 33))
  Preparing metadata (setup.py) ... done
Collecting accelerate==0.23.0
  Using cached accelerate-0.23.0-py3-none-any.whl (258 kB)
Collecting transformers==4.30.2
  Using cached transformers-4.30.2-py3-none-any.whl (7.2 MB)
Collecting diffusers[torch]==0.21.2
  Using cached diffusers-0.21.2.tar.gz (1.1 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Collecting setuptools>=40.8.0
        Using cached setuptools-69.0.3-py3-none-any.whl (819 kB)
      Collecting wheel
        Using cached wheel-0.42.0-py3-none-any.whl (65 kB)
      Installing collected packages: wheel, setuptools
      ERROR: Cannot set --home and --prefix together

      [notice] A new release of pip available: 22.2.1 -> 23.3.2
      [notice] To update, run: C:\StabilityMatrix\LoRA_Easy_Training_Scripts\sd_scripts\venv\Scripts\python.exe -m pip install --upgrade pip
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip available: 22.2.1 -> 23.3.2
[notice] To update, run: C:\StabilityMatrix\LoRA_Easy_Training_Scripts\sd_scripts\venv\Scripts\python.exe -m pip install --upgrade pip
Traceback (most recent call last):
  File "C:\StabilityMatrix\LoRA_Easy_Training_Scripts\installer\installer.py", line 221, in <module>
    main()
  File "C:\StabilityMatrix\LoRA_Easy_Training_Scripts\installer\installer.py", line 213, in main
    setup_normal(venv_pip)
  File "C:\StabilityMatrix\LoRA_Easy_Training_Scripts\installer\installer.py", line 92, in setup_normal
    subprocess.check_call(f"{venv_pip} install -r requirements.txt")
  File "C:\Users\jdroo\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'venv\Scripts\pip.exe install -r requirements.txt' returned non-zero exit status 1.
Press any key to continue . . .

C:\StabilityMatrix\LoRA_Easy_Training_Scripts>C:\StabilityMatrix\LoRA_Easy_Training_Scripts\sd_scripts\venv\Scripts\python.exe -m pip install --upgrade pip
Collecting pip
  Using cached pip-23.3.2-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
Successfully installed pip-23.3.2

[notice] A new release of pip available: 22.2.1 -> 23.3.2
[notice] To update, run: C:\StabilityMatrix\LoRA_Easy_Training_Scripts\sd_scripts\venv\Scripts\python.exe -m pip install --upgrade pip

C:\StabilityMatrix\LoRA_Easy_Training_Scripts>
```

**Comment by jdroo** [comment]
also I have a stupid thing to ask, but I don't know graphics card stuff... but when it asks "Are you using a 10X0 series card? (y/n):"... I do answer "n"...correct? I have an RTX 3070.... i know it's dumb, but just play along with me here! lmfao XD

**Comment by jdroo** [comment]
also it keeps saying pip upgraded correctly... so I'm confused why it keeps failing, do i need to do something to fix this error?

**Comment by derrian-distro** [comment]
> also I have a stupid thing to ask, but I don't know graphics card stuff... but when it asks "Are you using a 10X0 series card? (y/n):"... I do answer "n"...correct? I have an RTX 3070.... i know it's dumb, but just play along with me here! lmfao XD

yes, you would answer with n for that

as for your original question, what version of python are you running?
