### ISSUE TITLE
Error using the popup script

### ISSUE THREAD

**Issue by virtualghost** [derrian-distro/LoRA_Easy_Training_Scripts#18]
Hello. I've not been able to run the scripts at all due to this error.

lora_train_popup.py: error: ambiguous option: --lr_scheduler=cosine_with_restarts could match --lr_scheduler_num_cycles, --lr_scheduler_power
Traceback (most recent call last):
  File "C:\Users\ghost\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ghost\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "I:\lora\sd-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "I:\lora\sd-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "I:\lora\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "I:\lora\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['I:\\lora\\sd-scripts\\venv\\Scripts\\python.exe', 'lora_train_popup.py']' returned non-zero exit status 2.

I tried reinstalling Python and rerunning the scripts, in addition to using the script commands to install the dependencies and so on. Nothing worked, I'm up to date with the repository.

**Comment by derrian-distro** [comment]
There was a change very recently in sd-scripts that caused issues with that. I have fixed that within my test branch, an update should be released today.

**Comment by derrian-distro** [comment]
Hi, I updated the scripts, well overhauled them really, so you will likely need to reinstall everything from scratch, but it should solve your issue
