### ISSUE TITLE
NameError: name 'requests' is not defined

### ISSUE THREAD

**Issue by DrLightman** [derrian-distro/LoRA_Easy_Training_Scripts#186]
During installation:

```
Do you want to install the optional cudnn patch for faster training on high end 30X0 and 40X0 cards? (y/n): y
Traceback (most recent call last):
  File "D:\Loras\LoRA_Easy_Training_Scripts\installer\installer.py", line 221, in <module>
    main()
  File "D:\Loras\LoRA_Easy_Training_Scripts\installer\installer.py", line 215, in main
    setup_cudnn()
  File "D:\Loras\LoRA_Easy_Training_Scripts\installer\installer.py", line 162, in setup_cudnn
    r = requests.get(
NameError: name 'requests' is not defined
```

And crashed.

PS: I have an AMD card, I don't know if could be related.

**Comment by derrian-distro** [comment]
It's not related but my scripts do not work with amd regardless. Sd-scripts only supports Cuda, which is Nvidia only, so unfortunately, it's impossible for you to run on your card.

**Comment by DrLightman** [comment]
Ahhh, that's unfortunate.
