### ISSUE TITLE
NameError: name 'str2optimizer8bit_blockwise' is not defined

### ISSUE THREAD

**Issue by nonetrix** [derrian-distro/LoRA_Easy_Training_Scripts#2]
```
steps:   0%|                                                                                                                                                                              | 0/9000 [00:00<?, ?it/s]epoch 1/6
Traceback (most recent call last):
  File "/home/user/Documents/sd-scripts/lora_train_popup.py", line 329, in <module>
    main()
  File "/home/user/Documents/sd-scripts/lora_train_popup.py", line 180, in main
    train_network.train(args)
  File "/home/user/Documents/sd-scripts/train_network.py", line 318, in train
    optimizer.step()
  File "/home/user/.local/lib/python3.10/site-packages/accelerate/optimizer.py", line 134, in step
    self.scaler.step(self.optimizer, closure)
  File "/home/user/.local/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 341, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 288, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 68, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/torch/optim/optimizer.py", line 140, in wrapper
    out = func(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 265, in step
    self.update_step(group, p, gindex, pindex)
  File "/home/user/.local/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 506, in update_step
    F.optimizer_update_8bit_blockwise(
  File "/home/user/.local/lib/python3.10/site-packages/bitsandbytes/functional.py", line 858, in optimizer_update_8bit_blockwise
    str2optimizer8bit_blockwise[optimizer_name][0](
NameError: name 'str2optimizer8bit_blockwise' is not defined
steps:   0%|                                                                                                                                                                              | 0/9000 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/home/user/.local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/user/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/home/user/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', 'lora_train_popup.py']' returned non-zero exit status 1.
```

**Comment by nonetrix** [comment]
Might be related?
```
WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
CUDA SETUP: Loading binary /home/user/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
/home/user/.local/lib/python3.10/site-packages/bitsandbytes/cextension.py:48: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
```

**Comment by nonetrix** [comment]
```
Requirements Python >=3.8. Linux distribution (Ubuntu, MacOS, etc.) + CUDA > 10.0. LLM.int8() requires Turing or Ampere GPUs. Installation: pip install bitsandbytes
```
Seems my GPU is just too garbage

**Comment by derrian-distro** [comment]
If you don''t mind me asking, What graphics card do you have? I feel like that is an issue that can be resolved. when it comes to `WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)` it usually can be solved by putting the stuff in the bitsandbytes folder of sd-scripts into `AppData\Local\Programs\Python\Python310\Lib\site-packages\bitsandbytes` 

of course, if you hadn't done that in the first place, then try putting the stuff into `venv\Lib\site-packages\bitsandbytes` if that doesn't work then it very much might just be that your GPU is too outdated.
