### ISSUE TITLE
Keep tokens issue

### ISSUE THREAD

**Issue by zethfoxster** [derrian-distro/LoRA_Easy_Training_Scripts#204]
latest update greys out "keep tokens" 

Traceback (most recent call last):
  File "C:\Users\omega\Desktop\LORA TRAINING\LoRA_Easy_Training_Scripts\main_ui_files\MainWidget.py", line 294, in load_toml
    self.load_args(args)
  File "C:\Users\omega\Desktop\LORA TRAINING\LoRA_Easy_Training_Scripts\main_ui_files\MainWidget.py", line 252, in load_args
    self.subset_widget.load_args(args)
  File "C:\Users\omega\Desktop\LORA TRAINING\LoRA_Easy_Training_Scripts\main_ui_files\SubDatasetUI.py", line 409, in load_args
    elem.load_args(subset)
  File "C:\Users\omega\Desktop\LORA TRAINING\LoRA_Easy_Training_Scripts\main_ui_files\SubDatasetUI.py", line 217, in load_args
    self.widget.keep_tokens_spinbox.setValue(args["keep_tokens"])
KeyError: 'keep_tokens'

**Comment by Jelosus2** [comment]
It seems that the toml file that you are trying to load does not have the attribute **keep tokens**. Would you mind sharing your toml?

**Comment by zethfoxster** [comment]
any word when it will be pushed?

**Comment by derrian-distro** [comment]
no idea, I still have a lot I want to add to dev, and on top of that, I have to rewrite all of the tooltips and readme, as well as provide an update path as it will be changing to a completely different architecture, that being a client-server relationship

**Comment by Jelosus2** [comment]
Closing this as its been fixed on dev branch and will be soon merged into main branch.
