### ISSUE TITLE
How to update from Main branch to Dev branch

### ISSUE THREAD

**Issue by JBW2023** [derrian-distro/LoRA_Easy_Training_Scripts#208]
Hello, I am wondering how I can I install the Dev version with the latest update? I tried to download the **https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/archive/refs/heads/dev.zip** and running the install.bat commend but I am getting errors during the installation for Windows. Any help will be appreciated.

**Comment by JBW2023** [comment]
> Use git to clone it `git clone -b dev https://github.com/derrian-distro/LoRA_Easy_Training_Scripts` and run the install.bat

Got it, thanks, it works now, however I am facing another error while running the install.bat commend. This error occurs after answering the installer question:

"Are you using this locally? (y/n): " 
( I prompt y)

**FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\123\\.cache\\huggingface\\accelerate\\default_config.yaml'
Traceback (most recent call last):
  File "E:\Stable_Diffusion\LoRA_Easy_Training_Scripts-dev\LoRA_Easy_Training_Scripts\install.py", line 79, in <module>
    main()
  File "E:\Stable_Diffusion\LoRA_Easy_Training_Scripts-dev\LoRA_Easy_Training_Scripts\install.py", line 75, in main
    subprocess.check_call(f"{python} installer.py local", shell=sys.platform == "linux")
  File "C:\Users\123\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\Users\123\AppData\Local\Programs\Python\Python310\python.exe installer.py local' returned non-zero exit status 1.
Press any key to continue . . .**

**Comment by JBW2023** [comment]
Found the solution, thanks
**https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/issues/203**
