### ISSUE TITLE
RuntimeError: expected scalar type Half but found Float 

### ISSUE THREAD

**Issue by Extocine** [derrian-distro/LoRA_Easy_Training_Scripts#211]
Using the default settings, every time I try to run i keep getting this error. Same issue in Debian 12 & Windows 10

Traceback (most recent call last):                                                                                     File "C:\Users\Extocine\Desktop\ai\LoRA_Easy_Training_Scripts\sd_scripts\train_network.py", line 996, in <module>      trainer.train(args)                                                                                                File "C:\Users\Extocine\Desktop\ai\LoRA_Easy_Training_Scripts\sd_scripts\train_network.py", line 748, in train         latents = vae.encode(batch["images"].to(dtype=vae_dtype)).latent_dist.sample()                                     File "C:\Users\Extocine\Desktop\ai\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\diffusers\utils\accelerate_utils.py", line 46, in wrapper                                                                                   return method(self, *args, **kwargs)                                                                               File "C:\Users\Extocine\Desktop\ai\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\diffusers\models\autoencoder_kl.py", line 258, in encode                                                                                    h = self.encoder(x)                                                                                                File "C:\Users\Extocine\Desktop\ai\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl                                                                               return self._call_impl(*args, **kwargs)                                                                            File "C:\Users\Extocine\Desktop\ai\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl                                                                                       return forward_call(*args, **kwargs)                                                                               File "C:\Users\Extocine\Desktop\ai\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\diffusers\models\vae.py", line 141, in forward                                                                                              sample = down_block(sample)                                                                                        File "C:\Users\Extocine\Desktop\ai\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl                                                                               return self._call_impl(*args, **kwargs)                                                                            File "C:\Users\Extocine\Desktop\ai\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl                                                                                       return forward_call(*args, **kwargs)                                                                               File "C:\Users\Extocine\Desktop\ai\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 1247, in forward                                                                                  hidden_states = resnet(hidden_states, temb=None, scale=scale)                                                      File "C:\Users\Extocine\Desktop\ai\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl                                                                               return self._call_impl(*args, **kwargs)                                                                            File "C:\Users\Extocine\Desktop\ai\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl                                                                                       return forward_call(*args, **kwargs)                                                                               File "C:\Users\Extocine\Desktop\ai\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\diffusers\models\resnet.py", line 659, in forward                                                                                           hidden_states = self.conv2(hidden_states, scale)                                                                   File "C:\Users\Extocine\Desktop\ai\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl                                                                               return self._call_impl(*args, **kwargs)                                                                            File "C:\Users\Extocine\Desktop\ai\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl                                                                                       return forward_call(*args, **kwargs)                                                                               File "C:\Users\Extocine\Desktop\ai\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\diffusers\models\lora.py", line 163, in forward                                                                                             return F.conv2d(                                                                                                 KeyboardInterrupt                                                                                                    steps:   0%|                                                                                 | 0/80 [05:20<?, ?it/s] Failed to train because of error:                                                                                    Command '['C:\\Users\\Extocine\\Desktop\\ai\\LoRA_Easy_Training_Scripts\\sd_scripts\\venv\\Scripts\\python.exe', 'sd_scripts\\train_network.py', '--config_file=runtime_store\\config.toml', '--dataset_config=runtime_store\\dataset.toml']' returned non-zero exit status 3221225786.

**Comment by Jelosus2** [comment]
Hello, could you tell me what's your GPU model and provide the toml file?

**Comment by Extocine** [comment]
I have an RX 5700 XT

I'm assuming youre talking about the configuration file

```
[[subsets]]
num_repeats = 1
caption_extension = ".txt"
shuffle_caption = false
flip_aug = false
color_aug = false
random_crop = false
is_reg = false
image_dir = "/home/extocine/Programs/ai/LoRA_Easy_Training_Scripts/training"
keep_tokens = 0

[noise_args]

[sample_args]

[logging_args]

[general_args.args]
pretrained_model_name_or_path = "/home/extocine/Programs/ai/stable-diffusion-webui/models/Stable-diffusion/EasyFluffV11.2.safetensors"
mixed_precision = "fp16"
seed = 23
max_train_epochs = 1
max_data_loader_n_workers = 1
persistent_data_loader_workers = true
max_token_length = 225
prior_loss_weight = 1.0
clip_skip = 2

[general_args.dataset_args]
resolution = 512
batch_size = 1

[network_args.args]
network_dim = 32
network_alpha = 16.0
min_timestep = 0
max_timestep = 1000

[optimizer_args.args]
optimizer_type = "AdamW"
lr_scheduler = "cosine"
learning_rate = 0.0001
max_grad_norm = 1.0

[saving_args.args]
output_dir = "/home/extocine/Programs/ai/trained"
save_precision = "bf16"
save_model_as = "safetensors"
output_name = "extomodel"

[bucket_args.dataset_args]
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 1024
bucket_reso_steps = 64

[optimizer_args.args.optimizer_args]
weight_decay = "0.1"
betas = "0.9,0.99"```

**Comment by Jelosus2** [comment]
I see, AMD cant be used to train in most cases

**Comment by Extocine** [comment]
So I'm just outta luck?

**Comment by Jelosus2** [comment]
Sadly Nvidia has the whole monopoly of AI, you can use online alternatives like google colab, paperspace (if you are willing to pay for pro subscription) or trainers from AI sites like civitai, tensor.art, etc

**Comment by Extocine** [comment]
Alright, thanks anyway ^^
