### ISSUE TITLE
Unable to use CAWR (Cosine Annealing) scheduler while in flux branch

### ISSUE THREAD

**Issue by ROBKE223** [derrian-distro/LoRA_Easy_Training_Scripts#247]
Hello,

While trying to use CAWR I started to get this error, before updating the scheduler (around July-August) seemed to work fine while training with any optimizer, now after coming back it doesn't seem work. Tried to reinstall the entire program, but that did not seemed to help. I was wondering what could have caused this issue? I am adding the traceback I am getting while trying to use it. Other scheduler, such as RAWR (Rex annealing) seemed to work fine.

Traceback (most recent call last):
  File "..\LoRA_Easy_Training_Scripts\backend\sd_scripts\sdxl_train_network.py", line 210, in <module>
    trainer.train(args)
  File "..\LoRA_Easy_Training_Scripts\backend\sd_scripts\train_network.py", line 1185, in train
    optimizer.step()
  File "..\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\accelerate\optimizer.py", line 157, in step
    self.scaler.step(self.optimizer, closure)
  File "..\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\torch\amp\grad_scaler.py", line 454, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "..\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\torch\amp\grad_scaler.py", line 352, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "..\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\accelerate\optimizer.py", line 212, in patched_step
    return method(*args, **kwargs)
  File "..\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\LoraEasyCustomOptimizer\CosineAnnealingWarmRestarts.py", line 49, in wrapper
  instance._step_count += 1
AttributeError: 'AdamW8bit' object has no attribute '_step_count'

**Comment by Jelosus2** [comment]
@derrian-distro do you have any idea about this?

**Comment by derrian-distro** [comment]
honestly, no, and I've not had a ton of time to test it

**Comment by Jelosus2** [comment]
I've found this might be related to the version of torch installed

**Comment by Jelosus2** [comment]
I'm gonna close the issue due to inactivity. If you still need help or encounter a new problem you can open another issue
