### ISSUE TITLE
🪲[BUG] Error during FLUX model training – NotImplementedError with `to_empty()` after commit e43c7f0c0d211aebb767573e544614114ba43b8f

### ISSUE THREAD

**Issue by sashaok123** [derrian-distro/LoRA_Easy_Training_Scripts#249]
### Description:
After the latest commit `e43c7f0c0d211aebb767573e544614114ba43b8f`, an issue occurs when attempting to train FLUX models using the `LoRA Easy Training Scripts`. Specifically, the error is related to the usage of meta tensors and the `torch.nn.Module.to()` method, which leads to a `NotImplementedError`.

### Error Traceback:
```plaintext
Traceback (most recent call last):
  File "C:\!NeuralNetwork\LoRA_Easy_Training_Scripts\backend\sd_scripts\flux_train_network.py", line 519, in <module>
    trainer.train(args)
  File "C:\!NeuralNetwork\LoRA_Easy_Training_Scripts\backend\sd_scripts\train_network.py", line 354, in train
    model_version, text_encoder, vae, unet = self.load_target_model(args, weight_dtype, accelerator)
  File "C:\!NeuralNetwork\LoRA_Easy_Training_Scripts\backend\sd_scripts\flux_train_network.py", line 82, in load_target_model
    model = self.prepare_split_model(model, weight_dtype, accelerator)
  File "C:\!NeuralNetwork\LoRA_Easy_Training_Scripts\backend\sd_scripts\flux_train_network.py", line 127, in prepare_split_model
    flux_upper.to(accelerator.device, dtype=target_dtype)
  File "C:\!NeuralNetwork\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1340, in to
    return self._apply(convert)
  File "C:\!NeuralNetwork\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)
  File "C:\!NeuralNetwork\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 927, in _apply
    param_applied = fn(param)
  File "C:\!NeuralNetwork\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1333, in convert
    raise NotImplementedError: Cannot copy out of meta tensor; no data! Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta to a different device.
```

### Steps to Reproduce:
1. Pull the latest changes from the repository (commit `e43c7f0c0d211aebb767573e544614114ba43b8f`).
2. Run the training script as normal.
3. The above error is triggered during the training phase, specifically at the line involving `flux_upper.to()` in `flux_train_network.py`.

### Problem:
The error is caused because meta tensors cannot be moved using the `torch.nn.Module.to()` method. Instead, the recommended approach in such cases is to use `torch.nn.Module.to_empty()` to handle meta tensors.

### Suggested Fix:
In `flux_train_network.py`, at line 127, the following code:
```python
flux_upper.to(accelerator.device, dtype=target_dtype)
```

Should be replaced with:
```python
flux_upper = flux_upper.to_empty(device=accelerator.device)
```

This will ensure that the model is moved correctly to the desired device, avoiding the meta tensor issue. The issue is present after the aforementioned commit and was not observed in previous versions.

**Comment by derrian-distro** [comment]
hi, this is actually an issue for sd-scripts, which I don't maintain, I suggest opening up an issue over [there](https://github.com/kohya-ss/sd-scripts)

that being said, i've been meaning to update sd-scripts, so perhaps it's already fixed and I didn't pull updates
