### ISSUE TITLE
When "accelerate launch main.py " is run on Linux, the following prompt appears. What is the reason?

### ISSUE THREAD

**Issue by FanWuTuoBang** [derrian-distro/LoRA_Easy_Training_Scripts#25]
2023-02-27 00:43:39.383389: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-27 00:43:39.543670: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-27 00:43:39.580431: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-02-27 00:43:40.220278: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-02-27 00:43:40.220345: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-02-27 00:43:40.220355: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
/root/autodl-tmp/LoRA_Easy_Training_Scripts/sd_scripts/venv/bin/python3: can't open file 'main.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/root/autodl-tmp/LoRA_Easy_Training_Scripts/sd_scripts/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/root/autodl-tmp/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/root/autodl-tmp/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.8/site-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/root/autodl-tmp/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.8/site-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/root/autodl-tmp/LoRA_Easy_Training_Scripts/sd_scripts/venv/bin/python3', 'main.py', '--popup']' returned non-zero exit status 2.

**Comment by derrian-distro** [comment]
Looks like it's looking for tensorRT, which sd-scripts doesn't support. Hmm, I wonder why it is expecting it to be installed.

**Comment by cheesesteak45** [comment]
Getting a similar issue. If it makes a difference, I am using an AMD gpu, and I also went ahead and disabled xformers in the config.
```
accelerate launch main.py         ✔ 
2023-02-27 10:15:49.234289: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-27 10:15:50.353665: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-02-27 10:15:50.353688: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-02-27 10:15:52.946685: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-02-27 10:15:52.946743: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-02-27 10:15:52.946751: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/home/steve/Desktop/stable-diffusion-webui/LoRA_Easy_Training_Scripts/sd_scripts/main.py", line 9, in <module>
    import popup_questions
  File "/home/steve/Desktop/stable-diffusion-webui/LoRA_Easy_Training_Scripts/sd_scripts/popup_questions.py", line 1, in <module>
    from tkinter import messagebox
  File "/usr/lib/python3.10/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory
╭─────────────── Traceback (most recent call last) ────────────────╮
│ /home/steve/.local/bin/accelerate:8 in <module>                  │
│                                                                  │
│   5 from accelerate.commands.accelerate_cli import main          │
│   6 if __name__ == '__main__':                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys. │
│ ❱ 8 │   sys.exit(main())                                         │
│   9                                                              │
│                                                                  │
│ /home/steve/.local/lib/python3.10/site-packages/accelerate/comma │
│ nds/accelerate_cli.py:45 in main                                 │
│                                                                  │
│   42 │   │   exit(1)                                             │
│   43 │                                                           │
│   44 │   # Run                                                   │
│ ❱ 45 │   args.func(args)                                         │
│   46                                                             │
│   47                                                             │
│   48 if __name__ == "__main__":                                  │
│                                                                  │
│ /home/steve/.local/lib/python3.10/site-packages/accelerate/comma │
│ nds/launch.py:1104 in launch_command                             │
│                                                                  │
│   1101 │   elif defaults is not None and defaults.compute_enviro │
│   1102 │   │   sagemaker_launcher(defaults, args)                │
│   1103 │   else:                                                 │
│ ❱ 1104 │   │   simple_launcher(args)                             │
│   1105                                                           │
│   1106                                                           │
│   1107 def main():                                               │
│                                                                  │
│ /home/steve/.local/lib/python3.10/site-packages/accelerate/comma │
│ nds/launch.py:567 in simple_launcher                             │
│                                                                  │
│    564 │   process = subprocess.Popen(cmd, env=current_env)      │
│    565 │   process.wait()                                        │
│    566 │   if process.returncode != 0:                           │
│ ❱  567 │   │   raise subprocess.CalledProcessError(returncode=pr │
│    568                                                           │
│    569                                                           │
│    570 def multi_gpu_launcher(args):                             │
╰──────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['/usr/bin/python3', 'main.py']' 
returned non-zero exit status 1.
```

**Comment by derrian-distro** [comment]
I believe in your case, it's actually because tkinter isn't installed. For some reason tkinter isn't installed alongside python in Linux environments. It must be manually installed.

From what I know the tensorrt issue is something with accelerate, sd-scripts doesn't use tensorrt so it shouldn't cause issues.

**Comment by cheesesteak45** [comment]
Indeed that fixed it. My new error is `Failed to find img_folder, Please make sure path is correct.` but that should be easier to solve.

**Comment by derrian-distro** [comment]
Make sure you pass the folder the image folders are in, not the individual image folders named 1_name

**Comment by chewtoys** [comment]
> 

how did you solve the **img_folder** issue, having the same thing.

**Comment by chewtoys** [comment]
> Indeed that fixed it. My new error is `Failed to find img_folder, Please make sure path is correct.` but that should be easier to solve. Thanks for the help.

how did you solve the **img_folder** issue, having the same thing.
