### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by Larry3best** [derrian-distro/LoRA_Easy_Training_Scripts#250]
I get this error when trying to install with windows 11. I suspect that it might have to do with the space in the user I am logged in as. 
```
Traceback (most recent call last):
  File "E:\documents\sd.webui\LoRA_Easy_Training_Scripts\install.py", line 68, in <module>
    main()
  File "E:\documents\sd.webui\LoRA_Easy_Training_Scripts\install.py", line 40, in main
    subprocess.check_call(f"{python} -m venv venv", shell=sys.platform == "linux")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 364, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application
Press any key to continue . . .
```

**Comment by derrian-distro** [comment]
unfortunately, I don't think I can fix this one, spaces in paths is almost always the worst possible thing for a program to encounter, I handle spaces as best I can, but this is an error in python itself, so it's not something I can change

**Comment by Jelosus2** [comment]
Closing for inactivity, feel free to open a new issue if the problem persists after you try on a path without spaces
