### ISSUE TITLE
Possible issues with model training

### ISSUE THREAD

**Issue by alexgit256** [derrian-distro/LoRA_Easy_Training_Scripts#258]
Hi! It's a user from issue #255.

I seem to have three possibly related issues:
1) The trainer reports the loss value of nan.
2) None of the `Save only last`, `Save ratio`, `Save freq` options save anything but the last epoch for me.
3) Anything regarding flux is not being loaded from the toml file (see the bottom of the message).
I do believe there is something wrong with my installation.
Here are the logs:

```
E:\AI\derriandistro\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\diffusers\utils\outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
2024-11-25 22:52:31 WARNING  A matching Triton is not available, some optimizations will not be enabled   __init__.py:61
                             Traceback (most recent call last):
                               File
                             "E:\AI\derriandistro\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\
                             site-packages\xformers\__init__.py", line 57, in _is_triton_available
                                 import triton  # noqa
                             ModuleNotFoundError: No module named 'triton'
E:\AI\derriandistro\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\diffusers\utils\outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
E:\AI\derriandistro\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Traceback (most recent call last):
  File "E:\AI\derriandistro\LoRA_Easy_Training_Scripts\main_ui_files\MainUI.py", line 105, in load_toml
    self.args_widget.load_args(args, dataset_args)
  File "E:\AI\derriandistro\LoRA_Easy_Training_Scripts\main_ui_files\ArgsListUI.py", line 112, in load_args
    widget.load_args(args)
  File "E:\AI\derriandistro\LoRA_Easy_Training_Scripts\main_ui_files\NetworkUI.py", line 445, in load_args
    self.load_network_args(network_args)
  File "E:\AI\derriandistro\LoRA_Easy_Training_Scripts\main_ui_files\NetworkUI.py", line 500, in load_network_args
    self.add_network_arg(arg, value)
  File "E:\AI\derriandistro\LoRA_Easy_Training_Scripts\main_ui_files\NetworkUI.py", line 141, in add_network_arg
    self.network_args.append(OptimizerItem(arg_name=arg_name, arg_value=arg_value))
  File "E:\AI\derriandistro\LoRA_Easy_Training_Scripts\modules\OptimizerItem.py", line 28, in __init__
    self.arg_value_input.setText(self.arg_value or "")
TypeError: 'PySide6.QtWidgets.QLineEdit.setText' called with wrong argument types:
  PySide6.QtWidgets.QLineEdit.setText(bool)
Supported signatures:
  PySide6.QtWidgets.QLineEdit.setText(str)
flux_train_network.py
E:\AI\derriandistro\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\diffusers\utils\outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
2024-11-25 22:55:14 WARNING  A matching Triton is not available, some optimizations will not be enabled   __init__.py:61
                             Traceback (most recent call last):
                               File
                             "E:\AI\derriandistro\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\
                             site-packages\xformers\__init__.py", line 57, in _is_triton_available
                                 import triton  # noqa
                             ModuleNotFoundError: No module named 'triton'
E:\AI\derriandistro\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\diffusers\utils\outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
                    INFO     Loading settings from                                                    train_util.py:4422
                             E:\AI\derriandistro\LoRA_Easy_Training_Scripts\backend\runtime_store\con
                             fig.toml...
                    INFO     E:\AI\derriandistro\LoRA_Easy_Training_Scripts\backend\runtime_store\con train_util.py:4441
                             fig
2024-11-25 22:55:14 INFO     Checking the state dict: Diffusers or BFL, dev or schnell                  flux_utils.py:62
                    INFO     t5xxl_max_token_length: 512                                       flux_train_network.py:157
E:\AI\derriandistro\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
2024-11-25 22:55:15 INFO     Loading dataset config from                                            train_network.py:280
                             E:\AI\derriandistro\LoRA_Easy_Training_Scripts\backend\runtime_store\d
                             ataset.toml
                    INFO     prepare images.                                                          train_util.py:1942
                    INFO     get image size from name of cache files                                  train_util.py:1859
100%|██████████████████████████████████████████████████████████████████████████████████████████| 18/18 [00:00<?, ?it/s]
                    INFO     set image size from cache files: 0/18                                    train_util.py:1887
                    INFO     found directory C:/Users/Alex/Pictures/Datasets/Scar contains 18 image   train_util.py:1889
                             files
read caption: 100%|█████████████████████████████████████████████████████████████████| 18/18 [00:00<00:00, 11934.47it/s]
                    INFO     36 train images with repeating.                                          train_util.py:1983
                    INFO     0 reg images.                                                            train_util.py:1986
                    WARNING  no regularization images / 正則化画像が見つかりませんでした              train_util.py:1991
                    INFO     [Dataset 0]                                                              config_util.py:570
                               batch_size: 1
                               resolution: (512, 512)
                               enable_bucket: True
                               network_multiplier: 1.0
                               min_bucket_reso: 256
                               max_bucket_reso: 1024
                               bucket_reso_steps: 64
                               bucket_no_upscale: False

                               [Subset 0 of Dataset 0]
                                 image_dir: "C:/Users/Alex/Pictures/Datasets/Scar"
                                 image_count: 18
                                 num_repeats: 2
                                 shuffle_caption: False
                                 keep_tokens: 0
                                 keep_tokens_separator:
                                 caption_separator: ,
                                 secondary_separator: None
                                 enable_wildcard: False
                                 caption_dropout_rate: 0.0
                                 caption_dropout_every_n_epoches: 0
                                 caption_tag_dropout_rate: 0.0
                                 caption_prefix: None
                                 caption_suffix: None
                                 color_aug: False
                                 flip_aug: False
                                 face_crop_aug_range: None
                                 random_crop: False
                                 token_warmup_min: 1,
                                 token_warmup_step: 0,
                                 alpha_mask: False,
                                 is_reg: False
                                 class_tokens: None
                                 caption_extension: .txt


                    INFO     [Dataset 0]                                                              config_util.py:576
                    INFO     loading image sizes.                                                      train_util.py:914
100%|█████████████████████████████████████████████████████████████████████████████████| 18/18 [00:00<00:00, 298.41it/s]
                    INFO     make buckets                                                              train_util.py:937
                    INFO     number of images (including repeats) /                                    train_util.py:983
                             各bucketの画像枚数（繰り返し回数を含む）
                    INFO     bucket 0: resolution (384, 640), count: 6                                 train_util.py:988
                    INFO     bucket 1: resolution (448, 576), count: 4                                 train_util.py:988
                    INFO     bucket 2: resolution (512, 512), count: 8                                 train_util.py:988
                    INFO     bucket 3: resolution (640, 384), count: 16                                train_util.py:988
                    INFO     bucket 4: resolution (704, 320), count: 2                                 train_util.py:988
                    INFO     mean ar error (without repeats): 0.0752921960836257                       train_util.py:993
                    WARNING  max_token_length is not used in Flux training /                    flux_train_network.py:52
                             max_token_lengthはFluxのトレーニングでは使用されません
                    INFO     preparing accelerator                                                  train_network.py:345
E:\AI\derriandistro\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\accelerate\accelerator.py:488: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = torch.cuda.amp.GradScaler(**kwargs)
accelerator device: cuda
                    INFO     Checking the state dict: Diffusers or BFL, dev or schnell                  flux_utils.py:62
                    INFO     Building Flux model dev from BFL checkpoint                               flux_utils.py:116
                    INFO     Loading state dict from E:/AI/ComfyUI/models/unet/flux1-dev.safetensors   flux_utils.py:133
2024-11-25 22:55:16 INFO     Loaded Flux: <All keys matched successfully>                              flux_utils.py:145
debug clip_l - - -: E:/AI/ComfyUI/models/clip/clip_l.safetensors
debug pretrained_model_name_or_path - - -: E:/AI/ComfyUI/models/unet/flux1-dev.safetensors
                    INFO     Building CLIP                                                             flux_utils.py:165
                    INFO     Loading state dict from E:/AI/ComfyUI/models/clip/clip_l.safetensors      flux_utils.py:258
                    INFO     Loaded CLIP: <All keys matched successfully>                              flux_utils.py:261
debug t5xxl - - -: E:/AI/ComfyUI/models/text_encoders/t5xxl_fp8_e4m3fn.safetensors
                    INFO     Loading state dict from                                                   flux_utils.py:306
                             E:/AI/ComfyUI/models/text_encoders/t5xxl_fp8_e4m3fn.safetensors
                    INFO     Loaded T5xxl: <All keys matched successfully>                             flux_utils.py:309
                    INFO     Loaded fp8 T5XXL model                                            flux_train_network.py:103
debug ae - - -: E:/AI/ComfyUI/models/vae/ae.sft
                    INFO     Building AutoEncoder                                                      flux_utils.py:152
                    INFO     Loading state dict from E:/AI/ComfyUI/models/vae/ae.sft                   flux_utils.py:157
                    INFO     Loaded AE: <All keys matched successfully>                                flux_utils.py:160
import network module: networks.lora_flux
2024-11-25 22:55:18 INFO     [Dataset 0]                                                              train_util.py:2466
                    INFO     caching latents with caching strategy.                                   train_util.py:1039
                    INFO     caching latents...                                                       train_util.py:1084
  0%|                                                                                           | 0/18 [00:00<?, ?it/s]E:\AI\derriandistro\LoRA_Easy_Training_Scripts\backend\sd_scripts\library\flux_models.py:82: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:555.)
  h_ = nn.functional.scaled_dot_product_attention(q, k, v)
100%|██████████████████████████████████████████████████████████████████████████████████| 18/18 [00:02<00:00,  6.59it/s]
2024-11-25 22:55:20 INFO     move vae and unet to cpu to save memory                           flux_train_network.py:210
2024-11-25 22:55:21 INFO     move text encoders to gpu                                         flux_train_network.py:218
2024-11-25 22:55:34 INFO     prepare T5XXL for fp8: set to torch.float8_e4m3fn, set embeddings flux_train_network.py:498
                             to torch.float16, add hooks
                    INFO     [Dataset 0]                                                              train_util.py:2488
                    INFO     caching Text Encoder outputs with caching strategy.                      train_util.py:1218
                    INFO     checking cache validity...                                               train_util.py:1229
100%|██████████████████████████████████████████████████████████████████████████████████████████| 18/18 [00:00<?, ?it/s]
                    INFO     caching Text Encoder outputs...                                          train_util.py:1260
  0%|                                                                                           | 0/18 [00:00<?, ?it/s]
                   WARNING  T5 model is using fp8 weights for caching. This may affect the quality strategy_flux.py:150
                             of the cached outputs. /
                             T5モデルはfp8の重みを使用しています。これはキャッシュの品質に影響を与
                             える可能性があります。
100%|██████████████████████████████████████████████████████████████████████████████████| 18/18 [00:01<00:00,  9.28it/s]
2024-11-25 22:55:36 INFO     move t5XXL back to cpu                                            flux_train_network.py:258
2024-11-25 22:55:38 INFO     move vae and unet back to original device                         flux_train_network.py:263
                    INFO     create LoRA network. base dim (rank): 32, alpha: 16.0                      lora_flux.py:594
                    INFO     neuron dropout: p=None, rank dropout: p=None, module dropout: p=None       lora_flux.py:595
                    INFO     train all blocks only                                                      lora_flux.py:605
                    INFO     create LoRA for Text Encoder 1:                                            lora_flux.py:741
                    INFO     create LoRA for Text Encoder 1: 72 modules.                                lora_flux.py:744
                    INFO     create LoRA for FLUX all blocks: 304 modules.                              lora_flux.py:765
                    INFO     enable LoRA for text encoder: 72 modules                                   lora_flux.py:911
                    INFO     enable LoRA for U-Net: 304 modules                                         lora_flux.py:916
FLUX: Gradient checkpointing enabled. CPU offload: False
prepare optimizer, data loader etc.
                    INFO     Text Encoder 1 (CLIP-L): 72 modules, LR 0.0001                            lora_flux.py:1018
                    INFO     use AdamW optimizer | {'weight_decay': 0.1}                              train_util.py:4775
override steps. steps for 5 epochs is / 指定エポックまでのステップ数: 180
enable fp8 training for U-Net.
enable fp8 training for Text Encoder.
2024-11-25 22:57:39 INFO     prepare CLIP-L for fp8: set to torch.float8_e4m3fn, set           flux_train_network.py:469
                             embeddings to torch.float16
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 36
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 36
  num epochs / epoch数: 5
  batch size per device / バッチサイズ: 1
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 180
steps:   0%|                                                                                   | 0/180 [00:00<?, ?it/s]2024-11-25 22:57:53 INFO     unet dtype: torch.float8_e4m3fn, device: cuda:0                       train_network.py:1060
                    INFO     text_encoder [0] dtype: torch.float8_e4m3fn, device: cuda:0           train_network.py:1066
                    INFO     text_encoder [1] dtype: torch.float8_e4m3fn, device: cpu              train_network.py:1066

epoch 1/5
E:\AI\derriandistro\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\diffusers\utils\outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
2024-11-25 22:57:57 WARNING  A matching Triton is not available, some optimizations will not be enabled   __init__.py:61
                             Traceback (most recent call last):
                               File
                             "E:\AI\derriandistro\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\
                             site-packages\xformers\__init__.py", line 57, in _is_triton_available
                                 import triton  # noqa
                             ModuleNotFoundError: No module named 'triton'
E:\AI\derriandistro\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\diffusers\utils\outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
2024-11-25 22:57:58 INFO     epoch is incremented. current_epoch: 0, epoch: 1                          train_util.py:706
E:\AI\derriandistro\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\torch\utils\checkpoint.py:1399: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with device_autocast_ctx, torch.cpu.amp.autocast(**cpu_autocast_kwargs), recompute_context:  # type: ignore[attr-defined]
E:\AI\derriandistro\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\torch\utils\checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]
steps:  20%|████████████                                                | 36/180 [00:40<02:41,  1.12s/it, avr_loss=nan]
epoch 2/5
2024-11-25 22:58:33 INFO     epoch is incremented. current_epoch: 1, epoch: 2                          train_util.py:706
steps:  40%|████████████████████████                                    | 72/180 [01:16<01:54,  1.06s/it, avr_loss=nan]
epoch 3/5
2024-11-25 22:59:09 INFO     epoch is incremented. current_epoch: 2, epoch: 3                          train_util.py:706
steps:  60%|███████████████████████████████████▍                       | 108/180 [01:52<01:14,  1.04s/it, avr_loss=nan]
epoch 4/5
2024-11-25 22:59:45 INFO     epoch is incremented. current_epoch: 3, epoch: 4                          train_util.py:706
steps:  80%|███████████████████████████████████████████████▏           | 144/180 [02:27<00:36,  1.02s/it, avr_loss=nan]
epoch 5/5
2024-11-25 23:00:20 INFO     epoch is incremented. current_epoch: 4, epoch: 5                          train_util.py:706
steps: 100%|███████████████████████████████████████████████████████████| 180/180 [03:03<00:00,  1.02s/it, avr_loss=nan]
saving checkpoint: E:/AI/derriandistro/LoRA_Easy_Training_Scripts/loras\last.safetensors
E:\AI\derriandistro\LoRA_Easy_Training_Scripts\backend\sd_scripts\networks\lora_flux.py:861: FutureWarning: Positional args are being deprecated, use kwargs instead. Refer to https://pytorch.org/docs/main/generated/torch.nn.Module.html#torch.nn.Module.state_dict for details.
  return super().state_dict(destination, prefix, keep_vars)
2024-11-25 23:00:57 INFO     model saved.                                                          train_network.py:1298
steps: 100%|███████████████████████████████████████████████████████████| 180/180 [03:04<00:00,  1.02s/it, avr_loss=nan]
```

Here is the toml:

```
[[subsets]]
caption_extension = ".txt"
image_dir = "C:/Users/Alex/Pictures/Datasets/Scar"
name = "subset 1"
num_repeats = 2

[train_mode]
train_mode = "lora"

[general_args.args]
max_data_loader_n_workers = 1
persistent_data_loader_workers = true
pretrained_model_name_or_path = "E:/AI/ComfyUI/models/unet/flux1-dev.safetensors"
vae = "E:/AI/ComfyUI/models/vae/flux/flux1DevVAE_safetensors.safetensors"
clip_skip = 1
mixed_precision = "fp16"
fp8_base = true
gradient_checkpointing = true
seed = 144
max_token_length = 225
prior_loss_weight = 1.0
xformers = true
cache_latents = true
max_train_epochs = 5

[general_args.dataset_args]
resolution = [ 512, 512,]
batch_size = 1

[network_args.args]
network_dim = 32
network_alpha = 16.0
min_timestep = 0
max_timestep = 1000
cache_text_encoder_outputs = true

[textual_inversion_args.args]
token_string = ""
init_word = ""

[optimizer_args.args]
optimizer_type = "AdamW"
lr_scheduler = "cosine"
learning_rate = 0.0001
max_grad_norm = 1.0
loss_type = "l2"

[saving_args.args]
save_precision = "fp16"
save_model_as = "safetensors"
output_dir = "E:/AI/derriandistro/LoRA_Easy_Training_Scripts/loras"
save_n_epoch_ratio = 1
save_every_n_epochs = 1

[flux_args.args]
t5xxl_max_token_length = 512
timestep_sampling = "sigmoid"
sigmoid_scale = 1.0
discrete_flow_shift = false
weighting_scheme = "none"
guidance_scale = 1.0
model_prediction_type = "raw"
ae = "E:/AI/ComfyUI/models/vae/ae.sft"
clip_l = "E:/AI/ComfyUI/models/clip/clip_l.safetensors"
t5xxl = "E:/AI/ComfyUI/models/text_encoders/t5xxl_fp8_e4m3fn.safetensors"

[bucket_args.dataset_args]
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 1024
bucket_reso_steps = 64

[network_args.args.network_args]

[optimizer_args.args.optimizer_args]
weight_decay = "0.1"
```

**Comment by Jelosus2** [comment]
1 - The NaN loss means there's something in your config that is making the LoRA to break. Most probably related to the optimizer.
2 - If you want to save the last epoch only set the `Save Freq` option to the last number of epochs you're training.
3 -  I don't see any issue with loading the flux stuff. Maybe you could point it out if I skipped it

**Comment by Jelosus2** [comment]
Due to inactivity I'll close the issue, feel free to open a new issue or reopen this one in the future if you still have problems.
