### ISSUE TITLE
Error when running install.bat

### ISSUE THREAD

**Issue by Qpakskw82** [derrian-distro/LoRA_Easy_Training_Scripts#260]
Hello.Sorry to disturb. When running install.bat throws an error.(( Windows 10.
_

```
D:\kohya\Easy training scripts\LoRA_Easy_Training_Scripts>install.bat
Unable to copy 'C:\\Users\\etsio\\AppData\\Local\\Programs\\Python\\Python310\\venvlauncher.exe'
Unable to copy 'C:\\Users\\etsio\\AppData\\Local\\Programs\\Python\\Python310\\venvwlauncher.exe'
Error: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "D:\kohya\Easy training scripts\LoRA_Easy_Training_Scripts\install.py", line 68, in <module>
    main()
  File "D:\kohya\Easy training scripts\LoRA_Easy_Training_Scripts\install.py", line 40, in main
    subprocess.check_call(f"{python} -m venv venv", shell=sys.platform == "linux")
  File "C:\Users\etsio\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\Users\etsio\AppData\Local\Programs\Python\Python310\python.exe -m venv venv' returned non-zero exit status 1.
```

**Comment by Jelosus2** [comment]
Seems there might be some issue with your python installation. Could you screenshot the full content of the directory in the path `C:\Users\etsio\AppData\Local\Programs\Python\Python310`?

**Comment by Qpakskw82** [comment]
![Untitled](https://github.com/user-attachments/assets/2c9bab0d-63fa-4037-b503-8146b18f9cd3)

**Comment by Jelosus2** [comment]
Could you create a venv running `python -m venv venv` somewhere in your C: drive and then in your D: drive? Just to check if it's a permission error

**Comment by Qpakskw82** [comment]
Thank you very much!!! I completely deleted python (including folders in WindowsApp) and reinstalled. Everything worked!!!

**Comment by Jelosus2** [comment]
Nice! I'll close the issue then :)
