### ISSUE TITLE
SyntaxError: invalid character '·' (U+00B7)

### ISSUE THREAD

**Issue by clinchdev** [derrian-distro/LoRA_Easy_Training_Scripts#3]
**THE ERROR**
```
PS D:\sd-scripts> venv\Scripts\accelerate.exe launch --num_cpu_threads_per_process 12 lora_train_popup.py
  File "D:\sd-scripts\lora_train_popup.py", line 72
    <title>LoRA_Easy_Training_Scripts/lora_train_popup.py at main · derrian-distro/LoRA_Easy_Training_Scripts · GitHub</title>
                                                                  ^
SyntaxError: invalid character '·' (U+00B7)
Traceback (most recent call last):
  File "C:\Users\DASH\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\DASH\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\sd-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\sd-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "D:\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\sd-scripts\\venv\\Scripts\\python.exe', 'lora_train_popup.py']' returned non-zero exit status 1.
PS D:\sd-scripts>
```
**THE INSTALLATION**
Followed https://rentry.org/lora_train#instructions-for-running-the-training-script

**Comment by derrian-distro** [comment]
click code then click download on the main page, what you downloaded was the html file of the github page.

**Comment by clinchdev** [comment]
I'm likely ret*rded. Thank you,
