### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ihateyoudattebayo** [derrian-distro/LoRA_Easy_Training_Scripts#58]
Traceback (most recent call last):
  File "C:\Users\galax\LoRA_Easy_Training_Scripts\sd_scripts\train_network.py", line 783, in <module>
    train(args)
  File "C:\Users\galax\LoRA_Easy_Training_Scripts\sd_scripts\train_network.py", line 610, in train
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "C:\Users\galax\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\galax\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 381, in forward
    sample, res_samples = downsample_block(
  File "C:\Users\galax\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\galax\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 612, in forward
    hidden_states = attn(hidden_states, encoder_hidden_states=encoder_hidden_states).sample
  File "C:\Users\galax\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\galax\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\diffusers\models\attention.py", line 216, in forward
    hidden_states = block(hidden_states, context=encoder_hidden_states, timestep=timestep)
  File "C:\Users\galax\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\galax\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\diffusers\models\attention.py", line 484, in forward
    hidden_states = self.attn1(norm_hidden_states) + hidden_states
  File "C:\Users\galax\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\galax\LoRA_Easy_Training_Scripts\sd_scripts\library\train_util.py", line 1845, in forward_xformers
    out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None)  # 最適なのを選んでくれる
  File "C:\Users\galax\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 196, in memory_efficient_attention
    return _memory_efficient_attention(
  File "C:\Users\galax\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 294, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
  File "C:\Users\galax\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 314, in _memory_efficient_attention_forward
    out, *_ = op.apply(inp, needs_gradient=False)
  File "C:\Users\galax\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\xformers\ops\fmha\cutlass.py", line 175, in apply
    out, lse, rng_seed, rng_offset = cls.OPERATOR(
  File "C:\Users\galax\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\torch\_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: xformers::efficient_attention_forward_cutlass() expected at most 8 argument(s) but received 13 argument(s). Declaration: xformers::efficient_attention_forward_cutlass(Tensor query, Tensor key, Tensor value, Tensor? cu_seqlens_q, Tensor? cu_seqlens_k, int? max_seqlen_q, bool compute_logsumexp, bool causal) -> (Tensor, Tensor)
steps:   0%|                                                                                 | 0/12105 [00:14<?, ?it/s]
Failed to train because of error:
 Command '['C:\\Users\\galax\\LoRA_Easy_Training_Scripts\\sd_scripts\\venv\\Scripts\\python.exe', 'sd_scripts\\train_network.py', '--config_file=runtime_store\\config.toml', '--dataset_config=runtime_store\\dataset.toml']' returned non-zero exit status 1.

**Comment by derrian-distro** [comment]
this looks like a torch error of some kind, seemingly related to xformers. what graphics card do you have?

**Comment by Ihateyoudattebayo** [comment]
> this looks like a torch error of some kind, seemingly related to xformers. what graphics card do you have?

3060 ti mobile

**Comment by derrian-distro** [comment]
hmm, it shouldn't have an issue then, this is likely an issue more on the sd-scripts side of things, as that error comes after passing it over to sd-scripts. I suggest you open up an issue there as I unfortunately can't help you that much. since it failed however, you should still have the config files in the runtime_store folder so when you make the issue to sd-scripts I suggest you include them
