### ISSUE TITLE
[BUG]not running on debian linux with Titan xp using conda env

### ISSUE THREAD

**Issue by zwh20081** [derrian-distro/LoRA_Easy_Training_Scripts#6]
it reports this after catching latents:

import network module: networks.lora
Traceback (most recent call last):
  File "lora_train_command_line.py", line 397, in <module>
    main()
  File "lora_train_command_line.py", line 214, in main
    train_network.train(args)
  File "/root/autodl-tmp/sd-scripts/train_network.py", line 111, in train
    network = network_module.create_network(1.0, args.network_dim, args.network_alpha, vae, text_encoder, unet, **net_kwargs)
  File "/root/autodl-tmp/sd-scripts/networks/lora.py", line 58, in create_network
    network = LoRANetwork(text_encoder, unet, multiplier=multiplier, lora_dim=network_dim, alpha=network_alpha)
  File "/root/autodl-tmp/sd-scripts/networks/lora.py", line 99, in __init__
    def create_modules(prefix, root_module: torch.nn.Module, target_replace_modules) -> list[LoRAModule]:
TypeError: 'type' object is not subscriptable
Traceback (most recent call last):
  File "/root/miniconda3/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/root/miniconda3/lib/python3.8/site-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/root/miniconda3/lib/python3.8/site-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/root/miniconda3/bin/python', 'lora_train_command_line.py']' returned non-zero exit status 1.

**Comment by derrian-distro** [comment]
This is an issue with sd-scripts proper, once you reach cache latents it is no longer my code. That being said, you should probably update python to 3.10.6, as that is the version sd-scripts was built on.

**Comment by derrian-distro** [comment]
Gonna close the issue for now, if you have an issue with my script down the line, don't hesitate to open up another one.
