### ISSUE TITLE
Running run.sh returns an error

### ISSUE THREAD

**Issue by gLenahan** [derrian-distro/LoRA_Easy_Training_Scripts#65]
Using this on arch, followed the instructions to install and run the new ui version and it returns this error message.

Traceback (most recent call last):
File "/home/garrett/Desktop/LoRA_Easy_Training_ScriptsNew/main.py", line 14, in <module>
from main_ui_files.MainWidget import MainWidget
File "/home/garrett/Desktop/LoRA_Easy_Training_ScriptsNew/main_ui_files/MainWidget.py", line 6, in <module>
from main_ui_files import GeneralUI, OptimizerUI, NetworkUI, SavingUI, BucketUI, NoiseOffsetUI, SampleUI, LoggingUI, \
File "/home/garrett/Desktop/LoRA_Easy_Training_ScriptsNew/main_ui_files/SubDatasetUI.py", line 10, in <module>
class SubDatasetWidget(QtWidgets.QWidget):
File "/home/garrett/Desktop/LoRA_Easy_Training_ScriptsNew/main_ui_files/SubDatasetUI.py", line 81, in SubDatasetWidget
def get_subset_args(self, skip_check: bool = False) -> list[dict] | None:
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'NoneType'

The old version using popups still works just fine so I have no idea why the new version no longer does

**Comment by derrian-distro** [comment]
ah, linux must handle type hinting differently than windows I'll change up the type hint so that it *should* work

**Comment by gLenahan** [comment]
Thank you, the fix that you made seemed to fix the error as I was able to launch the new ui and train with no issues

**Comment by derrian-distro** [comment]
Great! I forgot to tell you when I pushed the change, my bad. Glad you noticed it yourself.
