### ISSUE TITLE
Error On Installing

### ISSUE THREAD

**Issue by yORmOmi** [derrian-distro/LoRA_Easy_Training_Scripts#71]
When I launch "install.py"
I also tried installing it while on administrator.
it sends an error:
```
Traceback (most recent call last):
  File "installer\installer.py", line 9, in <module>
    import requests
  File "C:\Users\irene\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Users\irene\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\__init__.py", line 39, in <module>
    "urllib3 v2.0 only supports OpenSSL 1.1.1+, currently "
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.1.0h  27 Mar 2018. See: https://github.com/urllib3/urllib3/issues/2168
```

PYTHON 3.7.0 / 3.10

**Comment by derrian-distro** [comment]
these scripts only work on python 3.10, that error is stating that you are on 3.7, I don't even know how you were able to get it to run, it usually stops when it doesn't detect that it is running in python 3.10
