### ISSUE TITLE
Permission denied issues

### ISSUE THREAD

**Issue by Nthompson096** [derrian-distro/LoRA_Easy_Training_Scripts#75]
Followed everything that was stated on the github page, the Distro i am using is Arch Linux.

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/cv2/../../lib64')}
  warn(
/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:105: UserWarning: /home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/cv2/../../lib64: did not contain libcudart.so as expected! Searching further paths...
  warn(
/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('@/tmp/.ICE-unix/1527,unix/windows98'), PosixPath('local/windows98')}
  warn(
/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/org/freedesktop/DisplayManager/Session0')}
  warn(
/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/etc/gtk/gtkrc'), PosixPath('/home/nicholas/.gtkrc')}
  warn(
Traceback (most recent call last):
  File "/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/train_network.py", line 864, in <module>
    train(args)
  File "/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/train_network.py", line 253, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/library/train_util.py", line 2623, in get_optimizer
    import bitsandbytes as bnb
  File "/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 41, in <module>
    lib = CUDALibrary_Singleton.get_instance().lib
  File "/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 37, in get_instance
    cls._instance.initialize()
  File "/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 15, in initialize
    binary_name = evaluate_cuda_setup()
  File "/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 123, in evaluate_cuda_setup
    cudart_path = determine_cuda_runtime_lib_path()
  File "/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py", line 117, in determine_cuda_runtime_lib_path
    cuda_runtime_libs.update(find_cuda_lib_in(value))
  File "/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py", line 53, in find_cuda_lib_in
    resolve_paths_list(paths_list_candidate)
  File "/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py", line 48, in resolve_paths_list
    return remove_non_existent_dirs(extract_candidate_paths(paths_list_candidate))
  File "/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py", line 23, in remove_non_existent_dirs
    raise exc
  File "/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py", line 19, in remove_non_existent_dirs
    if path.exists():
  File "/usr/lib/python3.10/pathlib.py", line 1290, in exists
    self.stat()
  File "/usr/lib/python3.10/pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
**PermissionError: [Errno 13] Permission denied: '/var/lib/lightdm-data/nicholas'
Failed to train because of error:
Command '['/home/nicholas/Desktop/SSD/AI/LoRA_Easy_Training_Scripts/sd_scripts/venv/bin/python', 'sd_scripts/train_network.py', '--config_file=runtime_store/config.toml', '--dataset_config=runtime_store/dataset.toml']' returned non-zero exit status 1.**

**Comment by derrian-distro** [comment]
that is an sd-scripts issue as it has reached the training section, I suggest bringing it there.

**Comment by Nthompson096** [comment]
Alright thank you.
