### ISSUE TITLE
install.bat failing to install accelerate

### ISSUE THREAD

**Issue by SyntaxError1871** [derrian-distro/LoRA_Easy_Training_Scripts#86]
install.bat is failing to install the accelerate plugin:

```
Setting up default config of accelerate
Traceback (most recent call last):
  File "D:\Applications\LoRA_Easy_Training_Scripts\installer\installer.py", line 167, in <module>
    main()
  File "D:\Applications\LoRA_Easy_Training_Scripts\installer\installer.py", line 129, in main
    shutil.copy(os.path.join('venv', 'Lib', 'site-packages', 'bitsandbytes', 'main.py'),
  File "C:\Users\COMPUTER\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\COMPUTER\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'venv\\Lib\\site-packages\\bitsandbytes\\main.py'
Press any key to continue . . .
```

Any ideas on what could be causing this?

**Comment by derrian-distro** [comment]
this is actually a bitsandbytes issue. seems like it isn't able to find the main.py folder within venv/lib/site-packages/bitsandbytes/main.py, which is odd to say the least. i'm not sure exactly why it failed, as I tried the installer a good 5 trillion times.
